package main

import (
	"fmt"
	"sort"
	"strings"

	"github.com/dave/jennifer/jen"
)

// CommandGroup groups operations by CLI resource.
type CommandGroup struct {
	Resource  string
	Commands  []GenCommand
}

// GenCommand represents one cobra command to emit.
type GenCommand struct {
	OperationID string
	Resource    string // cobra parent command name (e.g. "vendors")
	Command     string // subcommand name (e.g. "show")
	Summary     string
	Method      string // HTTP method
	Path        string  // raw path from spec (e.g. "/vendors/{id}")
	PathParams  []Parameter
	QueryParams []Parameter
	RequestBody *RequestBody
	IsPaginated bool
}

// groupOperations reads the spec and overrides to produce command groups.
func groupOperations(spec *Spec, overrides *Overrides) []CommandGroup {
	groupMap := make(map[string][]GenCommand)

	for path, item := range spec.Paths {
		for method, op := range item {
			if op.OperationID == "" {
				continue
			}
			cmd := buildCommand(op, method, path, overrides)
			if cmd == nil {
				continue
			}
			groupMap[cmd.Resource] = append(groupMap[cmd.Resource], *cmd)
		}
	}

	// Sort commands within each group by a stable order.
	var groups []CommandGroup
	for resource, cmds := range groupMap {
		sort.Slice(cmds, func(i, j int) bool {
			return cmds[i].Command < cmds[j].Command
		})
		groups = append(groups, CommandGroup{Resource: resource, Commands: cmds})
	}
	sort.Slice(groups, func(i, j int) bool {
		return groups[i].Resource < groups[j].Resource
	})
	return groups
}

func buildCommand(op Operation, method, path string, overrides *Overrides) *GenCommand {
	cmd := &GenCommand{
		OperationID: op.OperationID,
		Method:      method,
		Path:        path,
		Summary:     op.Summary,
	}

	// Split parameters into path and query.
	for _, p := range op.Parameters {
		if p.In == "path" {
			cmd.PathParams = append(cmd.PathParams, p)
		} else if p.In == "query" {
			cmd.QueryParams = append(cmd.QueryParams, p)
		}
	}
	cmd.RequestBody = op.RequestBody

	// Apply override if present.
	if ov, ok := overrides.Commands[op.OperationID]; ok {
		cmd.Resource = ov.Resource
		cmd.Command = ov.Command
		if ov.Summary != "" {
			cmd.Summary = ov.Summary
		}
		return cmd
	}

	// Auto-derive resource and command from path.
	cmd.Resource, cmd.Command = autoDerive(method, path)
	if cmd.Resource == "" {
		return nil // skip operations we can't classify
	}
	return cmd
}

// autoDerive maps a path+method to a CLI resource and command name.
func autoDerive(method, path string) (resource, command string) {
	segments := strings.Split(strings.Trim(path, "/"), "/")
	if len(segments) == 0 {
		return "", ""
	}
	resource = segments[0]
	hasID := strings.Contains(path, "{id}")

	switch method {
	case "get":
		if hasID {
			command = "show"
		} else {
			command = "list"
		}
	case "post":
		command = "create"
	case "patch":
		command = "update"
	case "delete":
		command = "delete"
	default:
		command = method
	}
	return resource, command
}

// emitGroup generates Go source for a command group using jennifer.
func emitGroup(group CommandGroup, spec *Spec, overrides *Overrides) (string, error) {
	f := jen.NewFile("cmd")
	f.HeaderComment("// Code generated by gencli. DO NOT EDIT.")

	for _, cmd := range group.Commands {
		emitCommand(f, cmd, overrides)
	}

	// Emit init() with proper cobra registration.
	f.Func().Id("init").Params().BlockFunc(func(g *jen.Group) {
		if len(group.Commands) == 0 {
			return
		}
		parentVar := group.Resource + "Cmd"
		g.Id(parentVar).Op(":=").Op("&").Qual("github.com/spf13/cobra", "Command").Values(jen.Dict{
			jen.Id("Use"):   jen.Lit(group.Resource),
			jen.Id("Short"): jen.Lit(titleCase(group.Resource) + " commands"),
		})
		g.Id(parentVar).Dot("AddCommand").Call(jen.ListFunc(func(l *jen.Group) {
			for _, cmd := range group.Commands {
				l.Id(cmdVarName(cmd))
			}
		}))
		g.Id("rootCmd").Dot("AddCommand").Call(jen.Id(parentVar))
	})

	return fmt.Sprintf("%#v", f), nil
}

// emitCommand emits a single cobra command variable + its RunE handler.
func emitCommand(f *jen.File, cmd GenCommand, overrides *Overrides) {
	varName := cmdVarName(cmd)
	cmdType := classifyCommand(cmd)

	// Command variable declaration (single declaration with all fields).
	dict := jen.Dict{
		jen.Id("Use"):   jen.Lit(cmd.Command + useArgsSuffix(cmdType, cmd)),
		jen.Id("Short"): jen.Lit(cmd.Summary),
		jen.Id("RunE"):  jen.Id(runHandlerName(cmd)),
	}
	// Args constraint for show/update/delete (requires 1 arg).
	if cmdType == "show" || cmdType == "update" || cmdType == "delete" {
		dict[jen.Id("Args")] = jen.Qual("github.com/spf13/cobra", "ExactArgs").Call(jen.Lit(1))
	}

	f.Var().Id(varName).Op("=").Op("&").Qual("github.com/spf13/cobra", "Command").Values(dict)

	// Emit flag variables and flag registration.
	emitFlags(f, cmd, overrides)

	// Emit the handler function.
	emitHandler(f, cmd, cmdType, overrides)
}

// classifyCommand determines which runner to use.
func classifyCommand(cmd GenCommand) string {
	switch cmd.Method {
	case "get":
		if len(cmd.PathParams) > 0 {
			// Check if the ID param is a string (e.g. locations).
			for _, p := range cmd.PathParams {
				if p.Name == "id" && p.Schema.Type == "string" {
					return "showStr"
				}
			}
			return "show"
		}
		return "list"
	case "post":
		if cmd.RequestBody != nil {
			return "create"
		}
		return "action" // e.g. merge
	case "patch":
		if cmd.RequestBody != nil {
			return "update"
		}
		return "action"
	case "delete":
		return "delete"
	default:
		return "list"
	}
}

func useArgsSuffix(cmdType string, cmd GenCommand) string {
	switch cmdType {
	case "show", "update", "delete":
		return " <id>"
	default:
		// Check if there are path params that aren't just {id}
		for _, p := range cmd.PathParams {
			if p.Name != "id" {
				return " <" + p.Name + ">"
			}
		}
		return ""
	}
}

func cmdVarName(cmd GenCommand) string {
	return toCamelCase(cmd.Resource) + titleCase(cmd.Command) + "Cmd"
}

func runHandlerName(cmd GenCommand) string {
	return "run" + titleCase(toCamelCase(cmd.Resource)) + titleCase(cmd.Command)
}

// emitFlags emits flag variable declarations and init wiring.
func emitFlags(f *jen.File, cmd GenCommand, overrides *Overrides) {
	// For now, emit path params as flags (e.g. --customer-id for drivers).
	// Query params and request body fields become flags too.
	// This is a simplified version — full body-field flag generation is a follow-up.
}

// emitHandler emits the RunE function that calls the appropriate runner.
func emitHandler(f *jen.File, cmd GenCommand, cmdType string, overrides *Overrides) {
	handlerName := runHandlerName(cmd)

	f.Func().Id(handlerName).Params(
		jen.Id("cmd").Op("*").Qual("github.com/spf13/cobra", "Command"),
		jen.Id("args").Index().Id("string"),
	).Id("error").BlockFunc(func(g *jen.Group) {
		switch cmdType {
		case "show":
			emitShowHandler(g, cmd)
		case "showStr":
			emitShowStrHandler(g, cmd)
		case "list":
			emitListHandler(g, cmd)
		case "create":
			emitCreateHandler(g, cmd)
		case "delete":
			emitDeleteHandler(g, cmd)
		default:
			emitActionHandler(g, cmd)
		}
	})
}

func emitShowHandler(g *jen.Group, cmd GenCommand) {
	resource := cmd.Resource
	g.Return(jen.Id("runShow").Call(
		jen.Id("cmd"), jen.Id("args"),
		jen.Lit(resource), jen.Lit("GET"),
		jen.Id("idPath").Call(jen.Lit(pathPrefix(cmd))),
		jen.Func().Params(
			jen.Id("ctx").Qual("context", "Context"),
			jen.Id("client").Op("*").Qual(wenmarPkg, "Client"),
			jen.Id("id").Id("int"),
		).Params(jen.Any(), jen.Error()).Block(
			jen.List(jen.Id("resp"), jen.Id("err")).Op(":=").Id("client").Dot(sdkMethodName(cmd.OperationID)).Call(jen.Id("ctx"), jen.Id("id")),
			jen.If(jen.Id("err").Op("!=").Nil()).Block(
				jen.Return(jen.Nil(), jen.Id("err")),
			),
			jen.Return(jen.Id("resp").Dot("JSON200"), jen.Nil()),
		),
	))
}

func emitShowStrHandler(g *jen.Group, cmd GenCommand) {
	resource := cmd.Resource
	g.Return(jen.Id("runShowStr").Call(
		jen.Id("cmd"), jen.Id("args"),
		jen.Lit(resource), jen.Lit("GET"),
		jen.Id("idPath").Call(jen.Lit(pathPrefix(cmd))),
		jen.Func().Params(
			jen.Id("ctx").Qual("context", "Context"),
			jen.Id("client").Op("*").Qual(wenmarPkg, "Client"),
			jen.Id("id").Id("string"),
		).Params(jen.Any(), jen.Error()).Block(
			jen.List(jen.Id("resp"), jen.Id("err")).Op(":=").Id("client").Dot(sdkMethodName(cmd.OperationID)).Call(jen.Id("ctx"), jen.Id("id")),
			jen.If(jen.Id("err").Op("!=").Nil()).Block(
				jen.Return(jen.Nil(), jen.Id("err")),
			),
			jen.Return(jen.Id("resp").Dot("JSON200"), jen.Nil()),
		),
	))
}

func emitListHandler(g *jen.Group, cmd GenCommand) {
	resource := cmd.Resource
	g.Return(jen.Id("runList").Call(
		jen.Id("cmd"),
		jen.Lit(resource),
		jen.Lit(cmd.Path),
		jen.Func().Params(
			jen.Id("ctx").Qual("context", "Context"),
			jen.Id("client").Op("*").Qual(wenmarPkg, "Client"),
		).Params(jen.Any(), jen.Error()).Block(
			jen.List(jen.Id("resp"), jen.Id("err")).Op(":=").Id("client").Dot(sdkMethodName(cmd.OperationID)).Call(jen.Id("ctx")),
			jen.If(jen.Id("err").Op("!=").Nil()).Block(
				jen.Return(jen.Nil(), jen.Id("err")),
			),
			jen.Return(jen.Id("resp").Dot("JSON200"), jen.Nil()),
		),
	))
}

func emitCreateHandler(g *jen.Group, cmd GenCommand) {
	resource := cmd.Resource
	g.Return(jen.Id("runCreate").Call(
		jen.Id("cmd"),
		jen.Lit(resource),
		jen.Lit(cmd.Path),
		jen.Lit(titleCase(resource) + " created."),
		jen.Func().Params().Params(jen.Any(), jen.Error()).Block(
			jen.Return(jen.Nil(), jen.Nil()), // placeholder — body construction is a follow-up
		),
		jen.Func().Params(
			jen.Id("ctx").Qual("context", "Context"),
			jen.Id("client").Op("*").Qual(wenmarPkg, "Client"),
			jen.Id("body").Any(),
		).Params(jen.Any(), jen.Error()).Block(
			jen.Return(jen.Nil(), jen.Nil()), // placeholder — sender is a follow-up
		),
	))
	_ = cmd
}

func emitDeleteHandler(g *jen.Group, cmd GenCommand) {
	resource := cmd.Resource
	label := titleCase(singularize(resource))
	g.Return(jen.Id("runDelete").Call(
		jen.Id("cmd"), jen.Id("args"),
		jen.Lit(label), jen.Lit(resource),
		jen.Lit(pathPrefix(cmd)),
		jen.False(), // dry-run flag wiring is a follow-up
		jen.Func().Params(
			jen.Id("ctx").Qual("context", "Context"),
			jen.Id("client").Op("*").Qual(wenmarPkg, "Client"),
			jen.Id("id").Id("int"),
		).Params(jen.Any(), jen.Error()).BlockFunc(func(bg *jen.Group) {
			bg.Return(jen.Id("client").Dot(titleCase(toCamelCase(cmd.OperationID))).Call(jen.Id("ctx"), jen.Id("id")))
		}),
	))
}

func emitActionHandler(g *jen.Group, cmd GenCommand) {
	// Generic action (merge, transfer, etc.) — falls back to a simple list call.
	emitListHandler(g, cmd)
}

// pathPrefix returns the path prefix for runShow/runDelete (e.g. "/vendors/").
func pathPrefix(cmd GenCommand) string {
	// Find the path up to and including the first path param's parent.
	path := cmd.Path
	idx := strings.Index(path, "{")
	if idx > 0 {
		return path[:idx]
	}
	return path + "/"
}

const wenmarPkg = "github.com/wenmar-pro/wenmar-sdk/go/wenmar"

// sdkMethodName converts an operationId (e.g. "list_vendors") to the
// SDK wrapper method name (e.g. "ListVendors").
func sdkMethodName(operationID string) string {
	parts := strings.Split(operationID, "_")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}

// Helpers

func titleCase(s string) string {
	if s == "" {
		return s
	}
	// Handle kebab-case (e.g. "work-orders" -> "WorkOrders")
	parts := strings.Split(s, "-")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}

func toCamelCase(s string) string {
	if s == "" {
		return s
	}
	// Handle kebab-case (e.g. "work-orders" -> "workOrders")
	parts := strings.Split(s, "-")
	result := parts[0]
	for i := 1; i < len(parts); i++ {
		if parts[i] == "" {
			continue
		}
		result += strings.ToUpper(parts[i][:1]) + parts[i][1:]
	}
	return result
}

func singularize(s string) string {
	if strings.HasSuffix(s, "ies") {
		return s[:len(s)-3] + "y"
	}
	if strings.HasSuffix(s, "s") {
		return s[:len(s)-1]
	}
	return s
}