// Code generated by gencli. DO NOT EDIT.

package cmd

import (
	"context"
	"fmt"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var workordertagsColor string
var workordertagsName string
var workordertagsCreateCmd = &cobra.Command{
	RunE:  runWorkordertagsCreate,
	Short: "Create a work order tag",
	Use:   "create",
}

func runWorkordertagsCreate(cmd *cobra.Command, args []string) error {
	return runCreate(cmd, "workordertags", "/work_order_tags", "Workordertag created.", func() (any, error) {
		req := wenmar.CreateWorkOrderTagRequest{
			Color: workordertagsColor,
			Name:  workordertagsName,
		}
		return req, nil
	}, func(ctx context.Context, client *wenmar.Client, body any) (any, error) {
		resp, err := client.CreateWorkOrderTag(ctx, body.(wenmar.CreateWorkOrderTagRequest))
		if err != nil {
			return nil, err
		}
		return resp.JSON201, nil
	})
}

var workordertagsDeleteCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runWorkordertagsDelete,
	Short: "Archive a work order tag by ID",
	Use:   "delete <id>",
}

func runWorkordertagsDelete(cmd *cobra.Command, args []string) error {
	return runActionNoBody(cmd, args, "workordertags", "PATCH", func(a []string) string {
		return fmt.Sprintf("/work_order_tags/%s/archive", a[0])
	}, "Workordertag delete.", func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.UpdateWorkOrderTagsArchive(ctx, id, wenmar.UpdateWorkOrderTagsArchiveRequest{})
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var workordertagsListCmd = &cobra.Command{
	Example: "wenmar workordertags list\n",
	RunE:    runWorkordertagsList,
	Short:   "List all work order tags",
	Use:     "list",
}

func runWorkordertagsList(cmd *cobra.Command, args []string) error {
	return runList(cmd, "workordertags", "/work_order_tags", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListWorkOrderTags(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var workordertagsUpdateCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runWorkordertagsUpdate,
	Short: "Update a work order tag by ID",
	Use:   "update <id>",
}

func runWorkordertagsUpdate(cmd *cobra.Command, args []string) error {
	return runUpdate(cmd, args, "workordertags", idPath("/work_order_tags/"), "Workordertag updated.", func(id int) (any, error) {
		req := wenmar.UpdateWorkOrderTagRequest{Name: workordertagsName}
		return req, nil
	}, func(ctx context.Context, client *wenmar.Client, id int, body any) (any, error) {
		resp, err := client.UpdateWorkOrderTag(ctx, id, body.(wenmar.UpdateWorkOrderTagRequest))
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var workordertagsCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "Manage work order tags",
	Use:   "workordertags",
}

func init() {
	workordertagsCreateCmd.Flags().StringVar(&workordertagsColor, "color", "", "Color (required)")
	workordertagsCreateCmd.MarkFlagRequired("color")
	workordertagsCreateCmd.Flags().StringVar(&workordertagsName, "name", "", "Name (required)")
	workordertagsCreateCmd.MarkFlagRequired("name")
	workordertagsUpdateCmd.Flags().StringVar(&workordertagsName, "name", "", "Name (required)")
	workordertagsUpdateCmd.MarkFlagRequired("name")
	workordertagsCmd.AddCommand(workordertagsCreateCmd, workordertagsDeleteCmd, workordertagsListCmd, workordertagsUpdateCmd)
	rootCmd.AddCommand(workordertagsCmd)
}
