// Code generated by gencli. DO NOT EDIT.

package cmd

import (
	"context"
	"fmt"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var statementsCustomerId int
var statementsListCmd = &cobra.Command{
	RunE:  runStatementsList,
	Short: "List statements for a customer, paginated via the Link header",
	Use:   "list",
}

func runStatementsList(cmd *cobra.Command, args []string) error {
	return runList(cmd, "statements", fmt.Sprintf("/customers/%d/statements", statementsCustomerId), func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListCustomersStatements(ctx, statementsCustomerId)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var statementsShowCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runStatementsShow,
	Short: "Show a single statement by ID",
	Use:   "show <id>",
}

func runStatementsShow(cmd *cobra.Command, args []string) error {
	return runShow(cmd, args, "statements", "GET", idPath("/statements/"), func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.ShowStatement(ctx, id)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var statementsCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "Manage statements",
	Use:   "statements",
}

func init() {
	statementsListCmd.Flags().IntVar(&statementsCustomerId, "customer-id", 0, "Customer ID (required)")
	statementsListCmd.MarkFlagRequired("customer-id")
	statementsCmd.AddCommand(statementsListCmd, statementsShowCmd)
	rootCmd.AddCommand(statementsCmd)
}
