// Code generated by gencli. DO NOT EDIT.

package cmd

import (
	"context"
	"fmt"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var driversCustomerId int
var driversDeleteDryRun bool
var driversFullName string
var driversPhone string
var driversCreateCmd = &cobra.Command{
	RunE:  runDriversCreate,
	Short: "Create a new driver for a customer",
	Use:   "create",
}

func runDriversCreate(cmd *cobra.Command, args []string) error {
	return runCreate(cmd, "drivers", fmt.Sprintf("/customers/%d/drivers", driversCustomerId), "Driver created.", func() (any, error) {
		req := wenmar.CreateDriverRequest{Driver: struct {
			FullName string `json:"full_name"`
			Phone    string `json:"phone"`
		}{
			FullName: driversFullName,
			Phone:    driversPhone,
		}}
		return req, nil
	}, func(ctx context.Context, client *wenmar.Client, body any) (any, error) {
		resp, err := client.CreateDriver(ctx, driversCustomerId, body.(wenmar.CreateDriverRequest))
		if err != nil {
			return nil, err
		}
		return resp.JSON201, nil
	})
}

var driversDeleteCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runDriversDelete,
	Short: "Delete a driver by ID",
	Use:   "delete <id>",
}

func runDriversDelete(cmd *cobra.Command, args []string) error {
	return runDelete(cmd, args, "Driver", "drivers", func(a []string) string {
		return fmt.Sprintf("/customers/%d/drivers/%s", driversCustomerId, a[0])
	}, driversDeleteDryRun, func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		return client.DeleteDriver(ctx, driversCustomerId, id)
	})
}

var driversListCmd = &cobra.Command{
	RunE:  runDriversList,
	Short: "List drivers for a customer, paginated via the Link header",
	Use:   "list",
}

func runDriversList(cmd *cobra.Command, args []string) error {
	return runList(cmd, "drivers", fmt.Sprintf("/customers/%d/drivers", driversCustomerId), func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListCustomersDrivers(ctx, driversCustomerId)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var driversShowCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runDriversShow,
	Short: "Show a single driver by ID",
	Use:   "show <id>",
}

func runDriversShow(cmd *cobra.Command, args []string) error {
	return runShow(cmd, args, "drivers", "GET", func(a []string) string {
		return fmt.Sprintf("/customers/%d/drivers/%s", driversCustomerId, a[0])
	}, func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.ShowDriver(ctx, driversCustomerId, id)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var driversUpdateCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runDriversUpdate,
	Short: "Update a driver by ID",
	Use:   "update <id>",
}

func runDriversUpdate(cmd *cobra.Command, args []string) error {
	return runUpdate(cmd, args, "drivers", func(a []string) string {
		return fmt.Sprintf("/customers/%d/drivers/%s", driversCustomerId, a[0])
	}, "Driver updated.", func(id int) (any, error) {
		req := wenmar.UpdateDriverRequest{Driver: struct {
			FullName string `json:"full_name"`
		}{FullName: driversFullName}}
		return req, nil
	}, func(ctx context.Context, client *wenmar.Client, id int, body any) (any, error) {
		resp, err := client.UpdateDriver(ctx, driversCustomerId, id, body.(wenmar.UpdateDriverRequest))
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var driversCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "Manage drivers",
	Use:   "drivers",
}

func init() {
	driversCreateCmd.Flags().IntVar(&driversCustomerId, "customer-id", 0, "Customer ID (required)")
	driversCreateCmd.MarkFlagRequired("customer-id")
	driversCreateCmd.Flags().StringVar(&driversFullName, "full-name", "", "Full Name (required)")
	driversCreateCmd.MarkFlagRequired("full-name")
	driversCreateCmd.Flags().StringVar(&driversPhone, "phone", "", "Driver phone")
	driversDeleteCmd.Flags().IntVar(&driversCustomerId, "customer-id", 0, "Customer ID (required)")
	driversDeleteCmd.MarkFlagRequired("customer-id")
	driversDeleteCmd.Flags().BoolVar(&driversDeleteDryRun, "dry-run", false, "Preview what would be deleted without making an API call")
	driversListCmd.Flags().IntVar(&driversCustomerId, "customer-id", 0, "Customer ID (required)")
	driversListCmd.MarkFlagRequired("customer-id")
	driversShowCmd.Flags().IntVar(&driversCustomerId, "customer-id", 0, "Customer ID (required)")
	driversShowCmd.MarkFlagRequired("customer-id")
	driversUpdateCmd.Flags().IntVar(&driversCustomerId, "customer-id", 0, "Customer ID (required)")
	driversUpdateCmd.MarkFlagRequired("customer-id")
	driversUpdateCmd.Flags().StringVar(&driversFullName, "full-name", "", "Driver full name")
	driversCmd.AddCommand(driversCreateCmd, driversDeleteCmd, driversListCmd, driversShowCmd, driversUpdateCmd)
	rootCmd.AddCommand(driversCmd)
}
