// Code generated by gencli. DO NOT EDIT.

package cmd

import (
	"context"
	"fmt"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var customertagsName string
var customertagsStatus string
var customertagsArchiveCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runCustomertagsArchive,
	Short: "Archive a customer tag by ID",
	Use:   "archive <id>",
}

func runCustomertagsArchive(cmd *cobra.Command, args []string) error {
	return runActionNoBody(cmd, args, "customertags", "PATCH", func(a []string) string {
		return fmt.Sprintf("/customer_tags/%s/archive", a[0])
	}, "Customertag archive.", func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.UpdateCustomerTagsArchive(ctx, id, wenmar.UpdateCustomerTagsArchiveRequest{})
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var customertagsCreateCmd = &cobra.Command{
	RunE:  runCustomertagsCreate,
	Short: "Create a customer tag",
	Use:   "create",
}

func runCustomertagsCreate(cmd *cobra.Command, args []string) error {
	return runCreate(cmd, "customertags", "/customer_tags", "Customertag created.", func() (any, error) {
		req := wenmar.CreateCustomerTagRequest{Name: customertagsName}
		return req, nil
	}, func(ctx context.Context, client *wenmar.Client, body any) (any, error) {
		resp, err := client.CreateCustomerTag(ctx, body.(wenmar.CreateCustomerTagRequest))
		if err != nil {
			return nil, err
		}
		return resp.JSON201, nil
	})
}

var customertagsDeleteCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runCustomertagsDelete,
	Short: "Trash a customer tag by ID",
	Use:   "delete <id>",
}

func runCustomertagsDelete(cmd *cobra.Command, args []string) error {
	return runActionNoBody(cmd, args, "customertags", "PATCH", func(a []string) string {
		return fmt.Sprintf("/customer_tags/%s/trash", a[0])
	}, "Customertag delete.", func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.UpdateCustomerTagsTrash(ctx, id, wenmar.UpdateCustomerTagsTrashRequest{})
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var customertagsListCmd = &cobra.Command{
	Example: "wenmar customertags list\n",
	RunE:    runCustomertagsList,
	Short:   "List all customer tags",
	Use:     "list",
}

func runCustomertagsList(cmd *cobra.Command, args []string) error {
	return runList(cmd, "customertags", "/customer_tags", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListCustomerTags(ctx, &wenmar.ListCustomerTagsParams{Status: strPtr(customertagsStatus)})
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var customertagsRestoreCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runCustomertagsRestore,
	Short: "Restore a customer tag to active",
	Use:   "restore <id>",
}

func runCustomertagsRestore(cmd *cobra.Command, args []string) error {
	return runActionNoBody(cmd, args, "customertags", "PATCH", func(a []string) string {
		return fmt.Sprintf("/customer_tags/%s/restore", a[0])
	}, "Customertag restore.", func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.UpdateCustomerTagsRestore(ctx, id, wenmar.UpdateCustomerTagsRestoreRequest{})
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var customertagsShowCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runCustomertagsShow,
	Short: "Show a single customer tag by ID",
	Use:   "show <id>",
}

func runCustomertagsShow(cmd *cobra.Command, args []string) error {
	return runShow(cmd, args, "customertags", "GET", idPath("/customer_tags/"), func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.ShowCustomerTag(ctx, id)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var customertagsUpdateCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runCustomertagsUpdate,
	Short: "Update a customer tag by ID",
	Use:   "update <id>",
}

func runCustomertagsUpdate(cmd *cobra.Command, args []string) error {
	return runUpdate(cmd, args, "customertags", idPath("/customer_tags/"), "Customertag updated.", func(id int) (any, error) {
		req := wenmar.UpdateCustomerTagRequest{Name: customertagsName}
		return req, nil
	}, func(ctx context.Context, client *wenmar.Client, id int, body any) (any, error) {
		resp, err := client.UpdateCustomerTag(ctx, id, body.(wenmar.UpdateCustomerTagRequest))
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var customertagsCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "Manage customer tags",
	Use:   "customertags",
}

func init() {
	customertagsCreateCmd.Flags().StringVar(&customertagsName, "name", "", "Name (required)")
	customertagsCreateCmd.MarkFlagRequired("name")
	customertagsListCmd.Flags().StringVar(&customertagsStatus, "status", "", "Status")
	customertagsUpdateCmd.Flags().StringVar(&customertagsName, "name", "", "Name (required)")
	customertagsUpdateCmd.MarkFlagRequired("name")
	customertagsCmd.AddCommand(customertagsArchiveCmd, customertagsCreateCmd, customertagsDeleteCmd, customertagsListCmd, customertagsRestoreCmd, customertagsShowCmd, customertagsUpdateCmd)
	rootCmd.AddCommand(customertagsCmd)
}
