// Code generated by gencli. DO NOT EDIT.

package cmd

import (
	"context"
	"fmt"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var vehiclesCustomerId int
var vehiclesDeleteDryRun bool
var vehiclesMake string
var vehiclesMode string
var vehiclesModel string
var vehiclesPage int
var vehiclesSourceVehicleId int
var vehiclesVin string
var vehiclesYear int
var vehiclesDecodeVinCmd = &cobra.Command{
	Args:    cobra.ExactArgs(1),
	Example: "wenmar vehicles decode-vin 1HGCM82633A004352\n",
	RunE:    runVehiclesDecodeVin,
	Short:   "Decode a VIN into make/model",
	Use:     "decode-vin <string>",
}

func runVehiclesDecodeVin(cmd *cobra.Command, args []string) error {
	return runList(cmd, "vehicles", "/vehicles/vin_decode", func(ctx context.Context, client *wenmar.Client) (any, error) {
		query := args[0]
		resp, err := client.DecodeVin(ctx, &wenmar.DecodeVinParams{Vin: strPtr(query)})
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var vehiclesDeleteCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runVehiclesDelete,
	Short: "Delete a vehicle by ID",
	Use:   "delete <id>",
}

func runVehiclesDelete(cmd *cobra.Command, args []string) error {
	return runDelete(cmd, args, "Vehicle", "vehicles", idPath("/vehicles/"), vehiclesDeleteDryRun, func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		return client.DeleteVehicle(ctx, id)
	})
}

var vehiclesDuplicatesCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runVehiclesDuplicates,
	Short: "Check for duplicate vehicles matching a VIN",
	Use:   "duplicates <string>",
}

func runVehiclesDuplicates(cmd *cobra.Command, args []string) error {
	return runList(cmd, "vehicles", "/vehicles/check_duplicate", func(ctx context.Context, client *wenmar.Client) (any, error) {
		query := args[0]
		resp, err := client.CheckVehicleDuplicate(ctx, &wenmar.CheckVehicleDuplicateParams{Vin: strPtr(query)})
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var vehiclesListCmd = &cobra.Command{
	Example: "wenmar vehicles list\nwenmar vehicles list --jq '.[].plate'\n",
	RunE:    runVehiclesList,
	Short:   "List all vehicles",
	Use:     "list",
}

func runVehiclesList(cmd *cobra.Command, args []string) error {
	return runList(cmd, "vehicles", "/vehicles", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListVehicles(ctx, &wenmar.ListVehiclesParams{
			CustomerId: intPtr(vehiclesCustomerId),
			Page:       intPtr(vehiclesPage),
		})
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var vehiclesLookupCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runVehiclesLookup,
	Short: "Search vehicles by make/model/plate/vin",
	Use:   "lookup <string>",
}

func runVehiclesLookup(cmd *cobra.Command, args []string) error {
	return runList(cmd, "vehicles", "/vehicles/lookup", func(ctx context.Context, client *wenmar.Client) (any, error) {
		query := args[0]
		resp, err := client.LookupVehicle(ctx, &wenmar.LookupVehicleParams{Query: strPtr(query)})
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var vehiclesMergeCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runVehiclesMerge,
	Short: "Merge a source vehicle into this keeper",
	Use:   "merge <id>",
}

func runVehiclesMerge(cmd *cobra.Command, args []string) error {
	return runAction(cmd, args, "vehicles", "POST", func(a []string) string {
		return fmt.Sprintf("/vehicles/%s/merges", a[0])
	}, "Vehicle action completed.", func(id int) (any, error) {
		req := wenmar.MergeVehicleRequest{SourceVehicleId: vehiclesSourceVehicleId}
		return req, nil
	}, func(ctx context.Context, client *wenmar.Client, id int, body any) (any, error) {
		resp, err := client.MergeVehicle(ctx, id, body.(wenmar.MergeVehicleRequest))
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var vehiclesPrefillCmd = &cobra.Command{
	RunE:  runVehiclesPrefill,
	Short: "Prefill vehicle data from a VIN",
	Use:   "prefill",
}

func runVehiclesPrefill(cmd *cobra.Command, args []string) error {
	return runList(cmd, "vehicles", "/vehicles/prefill", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.PrefillVehicle(ctx, &wenmar.PrefillVehicleParams{
			Make:  strPtr(vehiclesMake),
			Model: strPtr(vehiclesModel),
			Vin:   strPtr(vehiclesVin),
			Year:  intPtr(vehiclesYear),
		})
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var vehiclesShowCmd = &cobra.Command{
	Args:    cobra.ExactArgs(1),
	Example: "wenmar vehicles show 5\n",
	RunE:    runVehiclesShow,
	Short:   "Show a single vehicle by ID",
	Use:     "show <id>",
}

func runVehiclesShow(cmd *cobra.Command, args []string) error {
	return runShow(cmd, args, "vehicles", "GET", idPath("/vehicles/"), func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.ShowVehicle(ctx, id)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var vehiclesTransferCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runVehiclesTransfer,
	Short: "Transfer a vehicle to a new customer",
	Use:   "transfer <id>",
}

func runVehiclesTransfer(cmd *cobra.Command, args []string) error {
	return runAction(cmd, args, "vehicles", "POST", func(a []string) string {
		return fmt.Sprintf("/vehicles/%s/transfers", a[0])
	}, "Vehicle action completed.", func(id int) (any, error) {
		req := wenmar.TransferVehicleRequest{
			CustomerId: vehiclesCustomerId,
			Mode:       vehiclesMode,
		}
		return req, nil
	}, func(ctx context.Context, client *wenmar.Client, id int, body any) (any, error) {
		resp, err := client.TransferVehicle(ctx, id, body.(wenmar.TransferVehicleRequest))
		if err != nil {
			return nil, err
		}
		return resp.JSON201, nil
	})
}

var vehiclesWorkordersCmd = &cobra.Command{
	Aliases: []string{"work-orders"},
	Args:    cobra.ExactArgs(1),
	RunE:    runVehiclesWorkorders,
	Short:   "List a vehicle's work orders",
	Use:     "workorders <id>",
}

func runVehiclesWorkorders(cmd *cobra.Command, args []string) error {
	return runShow(cmd, args, "vehicles", "GET", func(a []string) string {
		return fmt.Sprintf("/vehicles/%s/work_orders", a[0])
	}, func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.ListVehiclesWorkOrders(ctx, id)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var vehiclesCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "Manage vehicles",
	Use:   "vehicles",
}

func init() {
	vehiclesDeleteCmd.Flags().BoolVar(&vehiclesDeleteDryRun, "dry-run", false, "Preview what would be deleted without making an API call")
	vehiclesListCmd.Flags().IntVar(&vehiclesCustomerId, "customer-id", 0, "Customer ID")
	vehiclesListCmd.Flags().IntVar(&vehiclesPage, "page", 0, "Page")
	vehiclesMergeCmd.Flags().IntVar(&vehiclesSourceVehicleId, "source-id", 0, "Source vehicle ID (required)")
	vehiclesMergeCmd.MarkFlagRequired("source-id")
	vehiclesPrefillCmd.Flags().StringVar(&vehiclesMake, "make", "", "Make")
	vehiclesPrefillCmd.Flags().StringVar(&vehiclesModel, "model", "", "Model")
	vehiclesPrefillCmd.Flags().StringVar(&vehiclesVin, "vin", "", "Vin")
	vehiclesPrefillCmd.Flags().IntVar(&vehiclesYear, "year", 0, "Year")
	vehiclesTransferCmd.Flags().IntVar(&vehiclesCustomerId, "customer-id", 0, "Customer ID (required)")
	vehiclesTransferCmd.MarkFlagRequired("customer-id")
	vehiclesTransferCmd.Flags().StringVar(&vehiclesMode, "mode", "vehicle_only", "Transfer mode (vehicle_only, vehicle_and_history, everything)")
	vehiclesCmd.AddCommand(vehiclesDecodeVinCmd, vehiclesDeleteCmd, vehiclesDuplicatesCmd, vehiclesListCmd, vehiclesLookupCmd, vehiclesMergeCmd, vehiclesPrefillCmd, vehiclesShowCmd, vehiclesTransferCmd, vehiclesWorkordersCmd)
	rootCmd.AddCommand(vehiclesCmd)
}
