// Code generated by gencli. DO NOT EDIT.

package cmd

import (
	"context"
	"fmt"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var servicecategoriesIcon string
var servicecategoriesName string
var servicecategoriesPosition int
var servicecategoriesServiceType string
var servicecategoriesArchiveCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runServicecategoriesArchive,
	Short: "Archive a service category (hidden from active lists, retained for history)",
	Use:   "archive <id>",
}

func runServicecategoriesArchive(cmd *cobra.Command, args []string) error {
	return runActionNoBody(cmd, args, "servicecategories", "PATCH", func(a []string) string {
		return fmt.Sprintf("/service_categories/%s/archive", a[0])
	}, "Servicecategory archive.", func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.ArchiveServiceCategory(ctx, id, wenmar.ArchiveServiceCategoryRequest{})
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var servicecategoriesCreateCmd = &cobra.Command{
	RunE:  runServicecategoriesCreate,
	Short: "Create a new service category",
	Use:   "create",
}

func runServicecategoriesCreate(cmd *cobra.Command, args []string) error {
	return runCreate(cmd, "servicecategories", "/service_categories", "Servicecategory created.", func() (any, error) {
		req := wenmar.CreateServiceCategoryRequest{ServiceCategory: struct {
			Icon        string `json:"icon"`
			Name        string `json:"name"`
			ServiceType string `json:"service_type"`
		}{
			Icon:        servicecategoriesIcon,
			Name:        servicecategoriesName,
			ServiceType: servicecategoriesServiceType,
		}}
		return req, nil
	}, func(ctx context.Context, client *wenmar.Client, body any) (any, error) {
		resp, err := client.CreateServiceCategory(ctx, body.(wenmar.CreateServiceCategoryRequest))
		if err != nil {
			return nil, err
		}
		return resp.JSON201, nil
	})
}

var servicecategoriesListCmd = &cobra.Command{
	Example: "wenmar servicecategories list\n",
	RunE:    runServicecategoriesList,
	Short:   "List all service categories",
	Use:     "list",
}

func runServicecategoriesList(cmd *cobra.Command, args []string) error {
	return runList(cmd, "servicecategories", "/service_categories", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListServiceCategories(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var servicecategoriesRestoreCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runServicecategoriesRestore,
	Short: "Restore a service category to active (from trashed or archived)",
	Use:   "restore <id>",
}

func runServicecategoriesRestore(cmd *cobra.Command, args []string) error {
	return runActionNoBody(cmd, args, "servicecategories", "PATCH", func(a []string) string {
		return fmt.Sprintf("/service_categories/%s/restore", a[0])
	}, "Servicecategory restore.", func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.RestoreServiceCategory(ctx, id, wenmar.RestoreServiceCategoryRequest{})
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var servicecategoriesSeedDefaultsCmd = &cobra.Command{
	RunE:  runServicecategoriesSeedDefaults,
	Short: "Seed default service categories for the account",
	Use:   "seed-defaults",
}

func runServicecategoriesSeedDefaults(cmd *cobra.Command, args []string) error {
	return runSeedAction(cmd, "servicecategories", "/service_categories/seed_defaults", "Default service categories seeded.", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.SeedDefaultsServiceCategories(ctx, wenmar.SeedDefaultsServiceCategoriesRequest{})
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var servicecategoriesTrashCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runServicecategoriesTrash,
	Short: "Soft-delete a service category (status: trashed, purgeable after 30 days)",
	Use:   "trash <id>",
}

func runServicecategoriesTrash(cmd *cobra.Command, args []string) error {
	return runActionNoBody(cmd, args, "servicecategories", "PATCH", func(a []string) string {
		return fmt.Sprintf("/service_categories/%s/trash", a[0])
	}, "Servicecategory trash.", func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.TrashServiceCategory(ctx, id, wenmar.TrashServiceCategoryRequest{})
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var servicecategoriesUpdateCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runServicecategoriesUpdate,
	Short: "Update a service category by ID",
	Use:   "update <id>",
}

func runServicecategoriesUpdate(cmd *cobra.Command, args []string) error {
	return runUpdate(cmd, args, "servicecategories", idPath("/service_categories/"), "Servicecategory updated.", func(id int) (any, error) {
		req := wenmar.UpdateServiceCategoryRequest{ServiceCategory: struct {
			Name     *string `json:"name,omitempty"`
			Position *int    `json:"position,omitempty"`
		}{
			Name:     strPtr(servicecategoriesName),
			Position: intPtr(servicecategoriesPosition),
		}}
		return req, nil
	}, func(ctx context.Context, client *wenmar.Client, id int, body any) (any, error) {
		resp, err := client.UpdateServiceCategory(ctx, id, body.(wenmar.UpdateServiceCategoryRequest))
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var servicecategoriesCmd = &cobra.Command{
	Aliases: []string{"service-categories", "sc"},
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "Manage service categories",
	Use:   "servicecategories",
}

func init() {
	servicecategoriesCreateCmd.Flags().StringVar(&servicecategoriesIcon, "icon", "wrench", "Icon (wrench, disc, engine, etc.)")
	servicecategoriesCreateCmd.Flags().StringVar(&servicecategoriesName, "name", "", "Name (required)")
	servicecategoriesCreateCmd.MarkFlagRequired("name")
	servicecategoriesCreateCmd.Flags().StringVar(&servicecategoriesServiceType, "service-type", "maintenance", "Service type (maintenance, repair, diagnostic, recall, sublet)")
	servicecategoriesUpdateCmd.Flags().StringVar(&servicecategoriesName, "name", "", "Name")
	servicecategoriesUpdateCmd.Flags().IntVar(&servicecategoriesPosition, "position", 0, "Position")
	servicecategoriesCmd.AddCommand(servicecategoriesArchiveCmd, servicecategoriesCreateCmd, servicecategoriesListCmd, servicecategoriesRestoreCmd, servicecategoriesSeedDefaultsCmd, servicecategoriesTrashCmd, servicecategoriesUpdateCmd)
	rootCmd.AddCommand(servicecategoriesCmd)
}
