// Code generated by gencli. DO NOT EDIT.

package cmd

import (
	"context"
	"fmt"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var woClosureReason string
var woCustomerId int
var woDeclineReason string
var woIntakeMethod string
var woOdometerIn int
var woOdometerOut int
var woPayerCustomerId int
var woSavedForLater bool
var woServicesVisibleToCustomer bool
var woSubStatusTypeId int
var woVehicleArrivedAt string
var woVehicleId int
var woWaitingForCustomer bool
var woWorkOrderId int
var woWorkOrderTagId int
var woCloseCmd = &cobra.Command{
	Args:    cobra.ExactArgs(1),
	Example: "wenmar wo close 100\n",
	RunE:    runWoClose,
	Short:   "Close a work order",
	Use:     "close <id>",
}

func runWoClose(cmd *cobra.Command, args []string) error {
	return runActionNoBody(cmd, args, "wo", "POST", func(a []string) string {
		return fmt.Sprintf("/work_orders/%s/close", a[0])
	}, "Work order close.", func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.CloseWorkOrder(ctx, id, wenmar.CloseWorkOrderRequest{})
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var woCompleteCmd = &cobra.Command{
	Args:    cobra.ExactArgs(1),
	Example: "wenmar wo complete 100\n",
	RunE:    runWoComplete,
	Short:   "Mark a work order complete",
	Use:     "complete <id>",
}

func runWoComplete(cmd *cobra.Command, args []string) error {
	return runAction(cmd, args, "wo", "POST", func(a []string) string {
		return fmt.Sprintf("/work_orders/%s/complete", a[0])
	}, "Work order action completed.", func(id int) (any, error) {
		req := wenmar.CompleteWorkOrderRequest{WorkOrderCompletionForm: struct {
			OdometerIn  int `json:"odometer_in"`
			OdometerOut int `json:"odometer_out"`
		}{
			OdometerIn:  woOdometerIn,
			OdometerOut: woOdometerOut,
		}}
		return req, nil
	}, func(ctx context.Context, client *wenmar.Client, id int, body any) (any, error) {
		resp, err := client.CompleteWorkOrder(ctx, id, body.(wenmar.CompleteWorkOrderRequest))
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var woCreateCmd = &cobra.Command{
	Example: "wenmar wo create --customer-id 42 --vehicle-id 5\n",
	RunE:    runWoCreate,
	Short:   "Create a new work order",
	Use:     "create",
}

func runWoCreate(cmd *cobra.Command, args []string) error {
	return runCreate(cmd, "wo", "/work_orders", "Work order created.", func() (any, error) {
		req := wenmar.CreateWorkOrderRequest{WorkOrder: struct {
			CustomerId int `json:"customer_id"`
			VehicleId  int `json:"vehicle_id"`
		}{
			CustomerId: woCustomerId,
			VehicleId:  woVehicleId,
		}}
		return req, nil
	}, func(ctx context.Context, client *wenmar.Client, body any) (any, error) {
		resp, err := client.CreateWorkOrder(ctx, body.(wenmar.CreateWorkOrderRequest))
		if err != nil {
			return nil, err
		}
		return resp.JSON201, nil
	})
}

var woDeclineCmd = &cobra.Command{
	Args:    cobra.ExactArgs(1),
	Example: "wenmar wo decline 100 --closure-reason \"Customer declined\"\n",
	RunE:    runWoDecline,
	Short:   "Close a work order as declined with a reason",
	Use:     "decline <id>",
}

func runWoDecline(cmd *cobra.Command, args []string) error {
	return runAction(cmd, args, "wo", "POST", func(a []string) string {
		return fmt.Sprintf("/work_orders/%s/decline", a[0])
	}, "Work order action completed.", func(id int) (any, error) {
		req := wenmar.DeclineWorkOrderRequest{ClosureReason: woClosureReason}
		return req, nil
	}, func(ctx context.Context, client *wenmar.Client, id int, body any) (any, error) {
		resp, err := client.DeclineWorkOrder(ctx, id, body.(wenmar.DeclineWorkOrderRequest))
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var woDeclineAllCmd = &cobra.Command{
	Example: "wenmar wo decline-all --work-order-id 100 --decline-reason \"Customer declined all\"\n",
	RunE:    runWoDeclineAll,
	Short:   "Decline all concerns on a work order",
	Use:     "decline-all",
}

func runWoDeclineAll(cmd *cobra.Command, args []string) error {
	return runCreate(cmd, "wo", fmt.Sprintf("/work_orders/%d/concerns/decline_all", woWorkOrderId), "Work order created.", func() (any, error) {
		req := wenmar.DeclineAllWorkOrderConcernsRequest{DeclineReason: woDeclineReason}
		return req, nil
	}, func(ctx context.Context, client *wenmar.Client, body any) (any, error) {
		resp, err := client.DeclineAllWorkOrderConcerns(ctx, woWorkOrderId, body.(wenmar.DeclineAllWorkOrderConcernsRequest))
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var woListCmd = &cobra.Command{
	Example: "wenmar wo list\nwenmar wo list --jq '.[].number'\nwenmar wo list --jq 'length'\n",
	RunE:    runWoList,
	Short:   "List all work orders, paginated via the Link header",
	Use:     "list",
}

func runWoList(cmd *cobra.Command, args []string) error {
	return runListPaginated(cmd, "wo", "/work_orders", func(ctx context.Context, client *wenmar.Client) (any, *wenmar.Paginator, error) {
		resp, err := client.ListWorkOrdersRaw(ctx, nil)
		if err != nil {
			return nil, nil, err
		}
		return resp.JSON200, client.PaginatorFromResponse(resp.HTTPResponse), nil
	})
}

var woPostToAccountCmd = &cobra.Command{
	Args:    cobra.ExactArgs(1),
	Example: "wenmar wo post-to-account 100\n",
	RunE:    runWoPostToAccount,
	Short:   "Post a work order to accounts receivable",
	Use:     "post-to-account <id>",
}

func runWoPostToAccount(cmd *cobra.Command, args []string) error {
	return runActionNoBody(cmd, args, "wo", "POST", func(a []string) string {
		return fmt.Sprintf("/work_orders/%s/post_to_account", a[0])
	}, "Work order post-to-account.", func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.PostWorkOrderToAccount(ctx, id, wenmar.PostWorkOrderToAccountRequest{})
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var woReopenCmd = &cobra.Command{
	Args:    cobra.ExactArgs(1),
	Example: "wenmar wo reopen 100\n",
	RunE:    runWoReopen,
	Short:   "Reopen a closed work order",
	Use:     "reopen <id>",
}

func runWoReopen(cmd *cobra.Command, args []string) error {
	return runActionNoBody(cmd, args, "wo", "POST", func(a []string) string {
		return fmt.Sprintf("/work_orders/%s/reopen", a[0])
	}, "Work order reopen.", func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.ReopenWorkOrder(ctx, id, wenmar.ReopenWorkOrderRequest{})
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var woSendEstimateCmd = &cobra.Command{
	Args:    cobra.ExactArgs(1),
	Example: "wenmar wo send-estimate 100\n",
	RunE:    runWoSendEstimate,
	Short:   "Send the estimate to the customer",
	Use:     "send-estimate <id>",
}

func runWoSendEstimate(cmd *cobra.Command, args []string) error {
	return runActionNoBody(cmd, args, "wo", "POST", func(a []string) string {
		return fmt.Sprintf("/work_orders/%s/send_estimate", a[0])
	}, "Work order send-estimate.", func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.SendWorkOrderEstimate(ctx, id, wenmar.SendWorkOrderEstimateRequest{})
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var woSendInvoiceSummaryCmd = &cobra.Command{
	Args:    cobra.ExactArgs(1),
	Example: "wenmar wo send-invoice-summary 100\n",
	RunE:    runWoSendInvoiceSummary,
	Short:   "Send the invoice summary to the customer",
	Use:     "send-invoice-summary <id>",
}

func runWoSendInvoiceSummary(cmd *cobra.Command, args []string) error {
	return runActionNoBody(cmd, args, "wo", "POST", func(a []string) string {
		return fmt.Sprintf("/work_orders/%s/send_invoice_summary", a[0])
	}, "Work order send-invoice-summary.", func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.SendWorkOrderInvoiceSummary(ctx, id, wenmar.SendWorkOrderInvoiceSummaryRequest{})
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var woSendReminderCmd = &cobra.Command{
	Args:    cobra.ExactArgs(1),
	Example: "wenmar wo send-reminder 100\n",
	RunE:    runWoSendReminder,
	Short:   "Send a reminder for the work order",
	Use:     "send-reminder <id>",
}

func runWoSendReminder(cmd *cobra.Command, args []string) error {
	return runActionNoBody(cmd, args, "wo", "POST", func(a []string) string {
		return fmt.Sprintf("/work_orders/%s/send_reminder", a[0])
	}, "Work order send-reminder.", func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.SendWorkOrderReminder(ctx, id, wenmar.SendWorkOrderReminderRequest{})
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var woStartCmd = &cobra.Command{
	Args:    cobra.ExactArgs(1),
	Example: "wenmar wo start 100\n",
	RunE:    runWoStart,
	Short:   "Start a work order (estimate -> in_progress)",
	Use:     "start <id>",
}

func runWoStart(cmd *cobra.Command, args []string) error {
	return runActionNoBody(cmd, args, "wo", "POST", func(a []string) string {
		return fmt.Sprintf("/work_orders/%s/start", a[0])
	}, "Work order start.", func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.StartWorkOrder(ctx, id, wenmar.StartWorkOrderRequest{})
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var woUpdateCmd = &cobra.Command{
	Args:    cobra.ExactArgs(1),
	Example: "wenmar wo update 100 --intake-method drop_off\n",
	RunE:    runWoUpdate,
	Short:   "Update a work order by ID",
	Use:     "update <id>",
}

func runWoUpdate(cmd *cobra.Command, args []string) error {
	return runUpdate(cmd, args, "wo", idPath("/work_orders/"), "Work order updated.", func(id int) (any, error) {
		req := wenmar.UpdateWorkOrderRequest{WorkOrder: struct {
			IntakeMethod              *string `json:"intake_method,omitempty"`
			PayerCustomerId           *int    `json:"payer_customer_id,omitempty"`
			SavedForLater             *bool   `json:"saved_for_later,omitempty"`
			ServicesVisibleToCustomer *bool   `json:"services_visible_to_customer,omitempty"`
			SubStatusTypeId           *int    `json:"sub_status_type_id,omitempty"`
			VehicleArrivedAt          *string `json:"vehicle_arrived_at,omitempty"`
			WaitingForCustomer        *bool   `json:"waiting_for_customer,omitempty"`
			WorkOrderTagId            *int    `json:"work_order_tag_id,omitempty"`
		}{
			IntakeMethod:              strPtr(woIntakeMethod),
			PayerCustomerId:           intPtr(woPayerCustomerId),
			SavedForLater:             boolPtr(woSavedForLater),
			ServicesVisibleToCustomer: boolPtr(woServicesVisibleToCustomer),
			SubStatusTypeId:           intPtr(woSubStatusTypeId),
			VehicleArrivedAt:          strPtr(woVehicleArrivedAt),
			WaitingForCustomer:        boolPtr(woWaitingForCustomer),
			WorkOrderTagId:            intPtr(woWorkOrderTagId),
		}}
		return req, nil
	}, func(ctx context.Context, client *wenmar.Client, id int, body any) (any, error) {
		resp, err := client.UpdateWorkOrder(ctx, id, body.(wenmar.UpdateWorkOrderRequest))
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var woVoidCmd = &cobra.Command{
	Args:    cobra.ExactArgs(1),
	Example: "wenmar wo void 100 --closure-reason \"Duplicate order\"\n",
	RunE:    runWoVoid,
	Short:   "Void a work order with a reason",
	Use:     "void <id>",
}

func runWoVoid(cmd *cobra.Command, args []string) error {
	return runAction(cmd, args, "wo", "POST", func(a []string) string {
		return fmt.Sprintf("/work_orders/%s/void", a[0])
	}, "Work order action completed.", func(id int) (any, error) {
		req := wenmar.VoidWorkOrderRequest{ClosureReason: woClosureReason}
		return req, nil
	}, func(ctx context.Context, client *wenmar.Client, id int, body any) (any, error) {
		resp, err := client.VoidWorkOrder(ctx, id, body.(wenmar.VoidWorkOrderRequest))
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var woCmd = &cobra.Command{
	Aliases: []string{"workorders", "work_orders"},
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "Manage work orders",
	Use:   "wo",
}

func init() {
	woCompleteCmd.Flags().IntVar(&woOdometerIn, "odometer-in", 0, "Odometer In (required)")
	woCompleteCmd.MarkFlagRequired("odometer-in")
	woCompleteCmd.Flags().IntVar(&woOdometerOut, "odometer-out", 0, "Odometer Out (required)")
	woCompleteCmd.MarkFlagRequired("odometer-out")
	woCreateCmd.Flags().IntVar(&woCustomerId, "customer-id", 0, "Customer ID (required)")
	woCreateCmd.MarkFlagRequired("customer-id")
	woCreateCmd.Flags().IntVar(&woVehicleId, "vehicle-id", 0, "Vehicle ID (required)")
	woCreateCmd.MarkFlagRequired("vehicle-id")
	woDeclineCmd.Flags().StringVar(&woClosureReason, "closure-reason", "", "Closure Reason (required)")
	woDeclineCmd.MarkFlagRequired("closure-reason")
	woDeclineAllCmd.Flags().IntVar(&woWorkOrderId, "work-order-id", 0, "Work Order ID (required)")
	woDeclineAllCmd.MarkFlagRequired("work-order-id")
	woDeclineAllCmd.Flags().StringVar(&woDeclineReason, "decline-reason", "", "Decline Reason (required)")
	woDeclineAllCmd.MarkFlagRequired("decline-reason")
	woUpdateCmd.Flags().StringVar(&woIntakeMethod, "intake-method", "", "Intake method (e.g. drop_off, walk_in)")
	woUpdateCmd.Flags().IntVar(&woPayerCustomerId, "payer-customer-id", 0, "Payer Customer ID")
	woUpdateCmd.Flags().BoolVar(&woSavedForLater, "saved-for-later", false, "Saved For Later")
	woUpdateCmd.Flags().BoolVar(&woServicesVisibleToCustomer, "services-visible-to-customer", false, "Services Visible To Customer")
	woUpdateCmd.Flags().IntVar(&woSubStatusTypeId, "sub-status-type-id", 0, "Sub Status Type ID")
	woUpdateCmd.Flags().StringVar(&woVehicleArrivedAt, "vehicle-arrived-at", "", "Vehicle Arrived At")
	woUpdateCmd.Flags().BoolVar(&woWaitingForCustomer, "waiting-for-customer", false, "Waiting For Customer")
	woUpdateCmd.Flags().IntVar(&woWorkOrderTagId, "work-order-tag-id", 0, "Work Order Tag ID")
	woVoidCmd.Flags().StringVar(&woClosureReason, "closure-reason", "", "Closure Reason (required)")
	woVoidCmd.MarkFlagRequired("closure-reason")
	woCmd.AddCommand(woCloseCmd, woCompleteCmd, woCreateCmd, woDeclineCmd, woDeclineAllCmd, woListCmd, woPostToAccountCmd, woReopenCmd, woSendEstimateCmd, woSendInvoiceSummaryCmd, woSendReminderCmd, woStartCmd, woUpdateCmd, woVoidCmd)
	rootCmd.AddCommand(woCmd)
}
