// Code generated by gencli. DO NOT EDIT.

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var workordersCustomerId int
var workordersDeleteDryRun bool
var workordersIntakeMethod string
var workordersVehicleId int
var workordersCreateCmd = &cobra.Command{
	RunE:  runWorkordersCreate,
	Short: "Create a new work order",
	Use:   "create",
}

func runWorkordersCreate(cmd *cobra.Command, args []string) error {
	return runCreate(cmd, "workorders", "/work_orders", "Work order created.", func() (any, error) {
		req := wenmar.CreateWorkOrderRequest{WorkOrder: struct {
			CustomerId int `json:"customer_id"`
			VehicleId  int `json:"vehicle_id"`
		}{
			CustomerId: workordersCustomerId,
			VehicleId:  workordersVehicleId,
		}}
		return req, nil
	}, func(ctx context.Context, client *wenmar.Client, body any) (any, error) {
		resp, err := client.CreateWorkOrder(ctx, body.(wenmar.CreateWorkOrderRequest))
		if err != nil {
			return nil, err
		}
		return resp.JSON201, nil
	})
}

var workordersDeleteCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runWorkordersDelete,
	Short: "Delete a work order by ID",
	Use:   "delete <id>",
}

func runWorkordersDelete(cmd *cobra.Command, args []string) error {
	return runDelete(cmd, args, "Work order", "workorders", idPath("/work_orders/"), workordersDeleteDryRun, func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		return client.DeleteWorkOrder(ctx, id)
	})
}

var workordersListCmd = &cobra.Command{
	RunE:  runWorkordersList,
	Short: "List all work orders, paginated via the Link header",
	Use:   "list",
}

func runWorkordersList(cmd *cobra.Command, args []string) error {
	return runListPaginated(cmd, "workorders", "/work_orders", func(ctx context.Context, client *wenmar.Client) (any, *wenmar.Paginator, error) {
		resp, err := client.ListWorkOrders(ctx)
		if err != nil {
			return nil, nil, err
		}
		return resp.JSON200, client.PaginatorFromResponse(resp.HTTPResponse), nil
	})
}

var workordersUpdateCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runWorkordersUpdate,
	Short: "Update a work order by ID",
	Use:   "update <id>",
}

func runWorkordersUpdate(cmd *cobra.Command, args []string) error {
	return runUpdate(cmd, args, "workorders", idPath("/work_orders/"), "Work order updated.", func(id int) (any, error) {
		req := wenmar.UpdateWorkOrderRequest{WorkOrder: struct {
			IntakeMethod string `json:"intake_method"`
		}{IntakeMethod: workordersIntakeMethod}}
		return req, nil
	}, func(ctx context.Context, client *wenmar.Client, id int, body any) (any, error) {
		resp, err := client.UpdateWorkOrder(ctx, id, body.(wenmar.UpdateWorkOrderRequest))
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var workordersCmd = &cobra.Command{
	Aliases: []string{"work_orders", "wo"},
	Args:    cobra.NoArgs,
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "Manage work orders",
	Use:   "workorders",
}

func init() {
	workordersCreateCmd.Flags().IntVar(&workordersCustomerId, "customer-id", 0, "Customer ID (required)")
	workordersCreateCmd.MarkFlagRequired("customer-id")
	workordersCreateCmd.Flags().IntVar(&workordersVehicleId, "vehicle-id", 0, "Vehicle ID (required)")
	workordersCreateCmd.MarkFlagRequired("vehicle-id")
	workordersDeleteCmd.Flags().BoolVar(&workordersDeleteDryRun, "dry-run", false, "Preview what would be deleted without making an API call")
	workordersUpdateCmd.Flags().StringVar(&workordersIntakeMethod, "intake-method", "", "Intake method (e.g. drop_off, walk_in)")
	workordersCmd.AddCommand(workordersCreateCmd, workordersDeleteCmd, workordersListCmd, workordersUpdateCmd)
	rootCmd.AddCommand(workordersCmd)
}
