// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var inventoryExtractionId string
var inventoryText string
var inventoryExtractCmd = &cobra.Command{
	Example: "wenmar inventory extract --extraction-id abc123 --text \"2x oil filter\"\n",
	RunE:    runInventoryExtract,
	Short:   "Extract inventory levels from text",
	Use:     "extract",
}

func runInventoryExtract(cmd *cobra.Command, args []string) error {
	return runCreate(cmd, "inventory", "/inventory_levels/extractions", "Inventory extraction started.", func() (any, error) {
		req := wenmar.CreateInventoryLevelExtractionRequest{
			ExtractionId: inventoryExtractionId,
			Text:         inventoryText,
		}
		return req, nil
	}, func(ctx context.Context, client *wenmar.Client, body any) (any, error) {
		resp, err := client.CreateInventoryLevelExtraction(ctx, body.(wenmar.CreateInventoryLevelExtractionRequest))
		if err != nil {
			return nil, err
		}
		return resp.JSON202, nil
	})
}

var inventoryCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "Manage inventory extractions",
	Use:   "inventory",
}

func init() {
	inventoryExtractCmd.Flags().StringVar(&inventoryExtractionId, "extraction-id", "", "Extraction ID (required)")
	inventoryExtractCmd.MarkFlagRequired("extraction-id")
	inventoryExtractCmd.Flags().StringVar(&inventoryText, "text", "", "Text (required)")
	inventoryExtractCmd.MarkFlagRequired("text")
	inventoryCmd.AddCommand(inventoryExtractCmd)
	rootCmd.AddCommand(inventoryCmd)
}
