// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	"fmt"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var storeCreditsAmount string
var storeCreditsMethod string
var storeCreditsStoreCreditId int
var storeCreditsCreateCmd = &cobra.Command{
	Annotations: map[string]string{"wenmar/op": "POST /store_credits/{store_credit_id}/refunds"},
	RunE:        runStoreCreditsCreate,
	Short:       "create",
	Use:         "create",
}

func runStoreCreditsCreate(cmd *cobra.Command, args []string) error {
	return runCreate(cmd, "store_credits", fmt.Sprintf("/store_credits/%d/refunds", storeCreditsStoreCreditId), "Store_credit created.", func() (any, error) {
		req := wenmar.CreateStoreCreditsRefundRequest{Refund: struct {
			Amount string `json:"amount"`
			Method string `json:"method"`
		}{
			Amount: storeCreditsAmount,
			Method: storeCreditsMethod,
		}}
		return req, nil
	}, func(ctx context.Context, client *wenmar.Client, body any) (any, error) {
		resp, err := client.CreateStoreCreditsRefund(ctx, storeCreditsStoreCreditId, body.(wenmar.CreateStoreCreditsRefundRequest))
		if err != nil {
			return nil, err
		}
		return resp.JSON201, nil
	})
}

var store_creditsCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "store_credits commands",
	Use:   "store_credits",
}

func init() {
	storeCreditsCreateCmd.Flags().IntVar(&storeCreditsStoreCreditId, "store-credit-id", 0, "Store Credit ID (required)")
	storeCreditsCreateCmd.MarkFlagRequired("store-credit-id")
	storeCreditsCreateCmd.Flags().StringVar(&storeCreditsAmount, "amount", "", "Amount (required)")
	storeCreditsCreateCmd.MarkFlagRequired("amount")
	storeCreditsCreateCmd.Flags().StringVar(&storeCreditsMethod, "method", "", "Method (required)")
	storeCreditsCreateCmd.MarkFlagRequired("method")
	store_creditsCmd.AddCommand(storeCreditsCreateCmd)
	rootCmd.AddCommand(store_creditsCmd)
}
