// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"fmt"
	cobra "github.com/spf13/cobra"
)

var subletPackagesUpdateCmd = &cobra.Command{
	RunE:  runSubletPackagesUpdate,
	Short: "deactivate",
	Use:   "update",
}

func runSubletPackagesUpdate(cmd *cobra.Command, args []string) error {
	// TODO: implement action handler for update_sublet_packages_deactivate
	return fmt.Errorf("action %s not yet generated", "update_sublet_packages_deactivate")
}

var sublet_packagesCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "sublet_packages commands",
	Use:   "sublet_packages",
}

func init() {
	sublet_packagesCmd.AddCommand(subletPackagesUpdateCmd)
	rootCmd.AddCommand(sublet_packagesCmd)
}
