// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var subStatusesCreateCmd = &cobra.Command{
	RunE:  runSubStatusesCreate,
	Short: "create",
	Use:   "create",
}

func runSubStatusesCreate(cmd *cobra.Command, args []string) error {
	return runSeedAction(cmd, "sub_statuses", "/sub_statuses", "Sub_statuse create.", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.CreateSubStatuse(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON201, nil
	})
}

var subStatusesListCmd = &cobra.Command{
	RunE:  runSubStatusesList,
	Short: "index",
	Use:   "list",
}

func runSubStatusesList(cmd *cobra.Command, args []string) error {
	return runList(cmd, "sub_statuses", "/sub_statuses", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListSubStatuses(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var subStatusesUpdateCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runSubStatusesUpdate,
	Short: "update",
	Use:   "update <id>",
}

func runSubStatusesUpdate(cmd *cobra.Command, args []string) error {
	return runUpdate(cmd, args, "sub_statuses", idPath("/sub_statuses/"), "Sub_statuse updated.", func(id int) (any, error) {
		return nil, nil
	}, func(ctx context.Context, client *wenmar.Client, id int, body any) (any, error) {
		return nil, nil
	})
}

var sub_statusesCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "sub_statuses commands",
	Use:   "sub_statuses",
}

func init() {
	sub_statusesCmd.AddCommand(subStatusesCreateCmd, subStatusesListCmd, subStatusesUpdateCmd)
	rootCmd.AddCommand(sub_statusesCmd)
}
