// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var preferencesListCmd = &cobra.Command{
	RunE:  runPreferencesList,
	Short: "show",
	Use:   "list",
}

func runPreferencesList(cmd *cobra.Command, args []string) error {
	return runList(cmd, "preferences", "/preferences", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListPreferences(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var preferencesCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "preferences commands",
	Use:   "preferences",
}

func init() {
	preferencesCmd.AddCommand(preferencesListCmd)
	rootCmd.AddCommand(preferencesCmd)
}
