// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var woCustomerId int
var woDeleteDryRun bool
var woIntakeMethod string
var woPayerCustomerId int
var woSavedForLater bool
var woSubStatusTypeId int
var woVehicleArrivedAt string
var woVehicleId int
var woWaitingForCustomer bool
var woWorkOrderTagId string
var woCreateCmd = &cobra.Command{
	Example: "wenmar wo create --customer-id 42 --vehicle-id 5\n",
	RunE:    runWoCreate,
	Short:   "Create a new work order",
	Use:     "create",
}

func runWoCreate(cmd *cobra.Command, args []string) error {
	return runCreate(cmd, "wo", "/work_orders", "Work order created.", func() (any, error) {
		req := wenmar.CreateWorkOrderRequest{WorkOrder: struct {
			CustomerId int `json:"customer_id"`
			VehicleId  int `json:"vehicle_id"`
		}{
			CustomerId: woCustomerId,
			VehicleId:  woVehicleId,
		}}
		return req, nil
	}, func(ctx context.Context, client *wenmar.Client, body any) (any, error) {
		resp, err := client.CreateWorkOrder(ctx, body.(wenmar.CreateWorkOrderRequest))
		if err != nil {
			return nil, err
		}
		return resp.JSON201, nil
	})
}

var woDeleteCmd = &cobra.Command{
	Args:    cobra.ExactArgs(1),
	Example: "wenmar wo delete 100 --dry-run\n",
	RunE:    runWoDelete,
	Short:   "Delete a work order by ID",
	Use:     "delete <id>",
}

func runWoDelete(cmd *cobra.Command, args []string) error {
	return runDelete(cmd, args, "Work order", "wo", idPath("/work_orders/"), woDeleteDryRun, func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		return client.DeleteWorkOrder(ctx, id)
	})
}

var woListCmd = &cobra.Command{
	Example: "wenmar wo list\nwenmar wo list --jq '.[].number'\nwenmar wo list --jq 'length'\n",
	RunE:    runWoList,
	Short:   "List all work orders, paginated via the Link header",
	Use:     "list",
}

func runWoList(cmd *cobra.Command, args []string) error {
	return runListPaginated(cmd, "wo", "/work_orders", func(ctx context.Context, client *wenmar.Client) (any, *wenmar.Paginator, error) {
		resp, err := client.ListWorkOrdersRaw(ctx, nil)
		if err != nil {
			return nil, nil, err
		}
		return resp.JSON200, client.PaginatorFromResponse(resp.HTTPResponse), nil
	})
}

var woUpdateCmd = &cobra.Command{
	Args:    cobra.ExactArgs(1),
	Example: "wenmar wo update 100 --intake-method drop_off\n",
	RunE:    runWoUpdate,
	Short:   "Update a work order by ID",
	Use:     "update <id>",
}

func runWoUpdate(cmd *cobra.Command, args []string) error {
	return runUpdate(cmd, args, "wo", idPath("/work_orders/"), "Work order updated.", func(id int) (any, error) {
		req := wenmar.UpdateWorkOrderRequest{WorkOrder: struct {
			IntakeMethod       *string `json:"intake_method,omitempty"`
			PayerCustomerId    *int    `json:"payer_customer_id,omitempty"`
			SavedForLater      *bool   `json:"saved_for_later,omitempty"`
			SubStatusTypeId    *int    `json:"sub_status_type_id,omitempty"`
			VehicleArrivedAt   *string `json:"vehicle_arrived_at,omitempty"`
			WaitingForCustomer *bool   `json:"waiting_for_customer,omitempty"`
			WorkOrderTagId     *string `json:"work_order_tag_id,omitempty"`
		}{
			IntakeMethod:       strPtr(woIntakeMethod),
			PayerCustomerId:    intPtr(woPayerCustomerId),
			SavedForLater:      boolPtr(woSavedForLater),
			SubStatusTypeId:    intPtr(woSubStatusTypeId),
			VehicleArrivedAt:   strPtr(woVehicleArrivedAt),
			WaitingForCustomer: boolPtr(woWaitingForCustomer),
			WorkOrderTagId:     strPtr(woWorkOrderTagId),
		}}
		return req, nil
	}, func(ctx context.Context, client *wenmar.Client, id int, body any) (any, error) {
		resp, err := client.UpdateWorkOrder(ctx, id, body.(wenmar.UpdateWorkOrderRequest))
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var woCmd = &cobra.Command{
	Aliases: []string{"workorders", "work_orders"},
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "Manage work orders",
	Use:   "wo",
}

func init() {
	woCreateCmd.Flags().IntVar(&woCustomerId, "customer-id", 0, "Customer ID (required)")
	woCreateCmd.MarkFlagRequired("customer-id")
	woCreateCmd.Flags().IntVar(&woVehicleId, "vehicle-id", 0, "Vehicle ID (required)")
	woCreateCmd.MarkFlagRequired("vehicle-id")
	woDeleteCmd.Flags().BoolVar(&woDeleteDryRun, "dry-run", false, "Preview what would be deleted without making an API call")
	woUpdateCmd.Flags().StringVar(&woIntakeMethod, "intake-method", "", "Intake method (e.g. drop_off, walk_in)")
	woUpdateCmd.Flags().IntVar(&woPayerCustomerId, "payer-customer-id", 0, "Payer Customer ID")
	woUpdateCmd.Flags().BoolVar(&woSavedForLater, "saved-for-later", false, "Saved For Later")
	woUpdateCmd.Flags().IntVar(&woSubStatusTypeId, "sub-status-type-id", 0, "Sub Status Type ID")
	woUpdateCmd.Flags().StringVar(&woVehicleArrivedAt, "vehicle-arrived-at", "", "Vehicle Arrived At")
	woUpdateCmd.Flags().BoolVar(&woWaitingForCustomer, "waiting-for-customer", false, "Waiting For Customer")
	woUpdateCmd.Flags().StringVar(&woWorkOrderTagId, "work-order-tag-id", "", "Work Order Tag ID")
	woCmd.AddCommand(woCreateCmd, woDeleteCmd, woListCmd, woUpdateCmd)
	rootCmd.AddCommand(woCmd)
}
