// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var inventoryLevelsDeleteDryRun bool
var inventoryLevelsCreateCmd = &cobra.Command{
	RunE:  runInventoryLevelsCreate,
	Short: "create",
	Use:   "create",
}

func runInventoryLevelsCreate(cmd *cobra.Command, args []string) error {
	return runSeedAction(cmd, "inventory_levels", "/inventory_levels", "Inventory_level create.", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.CreateInventoryLevel(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON201, nil
	})
}

var inventoryLevelsDeleteCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runInventoryLevelsDelete,
	Short: "destroy",
	Use:   "delete <id>",
}

func runInventoryLevelsDelete(cmd *cobra.Command, args []string) error {
	return runDelete(cmd, args, "Inventory_level", "inventory_levels", idPath("/inventory_levels/"), inventoryLevelsDeleteDryRun, func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		return client.DeleteInventoryLevel(ctx, id)
	})
}

var inventoryLevelsListCmd = &cobra.Command{
	RunE:  runInventoryLevelsList,
	Short: "index",
	Use:   "list",
}

func runInventoryLevelsList(cmd *cobra.Command, args []string) error {
	return runList(cmd, "inventory_levels", "/inventory_levels", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListInventoryLevels(ctx, nil)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var inventoryLevelsShowCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runInventoryLevelsShow,
	Short: "show",
	Use:   "show <id>",
}

func runInventoryLevelsShow(cmd *cobra.Command, args []string) error {
	return runShow(cmd, args, "inventory_levels", "GET", idPath("/inventory_levels/"), func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.ShowInventoryLevel(ctx, id)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var inventoryLevelsUpdateCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runInventoryLevelsUpdate,
	Short: "update",
	Use:   "update <id>",
}

func runInventoryLevelsUpdate(cmd *cobra.Command, args []string) error {
	return runUpdate(cmd, args, "inventory_levels", idPath("/inventory_levels/"), "Inventory_level updated.", func(id int) (any, error) {
		return nil, nil
	}, func(ctx context.Context, client *wenmar.Client, id int, body any) (any, error) {
		return nil, nil
	})
}

var inventory_levelsCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "inventory_levels commands",
	Use:   "inventory_levels",
}

func init() {
	inventoryLevelsDeleteCmd.Flags().BoolVar(&inventoryLevelsDeleteDryRun, "dry-run", false, "Preview what would be deleted without making an API call")
	inventory_levelsCmd.AddCommand(inventoryLevelsCreateCmd, inventoryLevelsDeleteCmd, inventoryLevelsListCmd, inventoryLevelsShowCmd, inventoryLevelsUpdateCmd)
	rootCmd.AddCommand(inventory_levelsCmd)
}
