// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var inspectionsDeleteDryRun bool
var inspectionsCreateCmd = &cobra.Command{
	RunE:  runInspectionsCreate,
	Short: "create",
	Use:   "create",
}

func runInspectionsCreate(cmd *cobra.Command, args []string) error {
	return runSeedAction(cmd, "inspections", "/inspections", "Inspection create.", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.CreateInspection(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON201, nil
	})
}

var inspectionsDeleteCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runInspectionsDelete,
	Short: "destroy",
	Use:   "delete <id>",
}

func runInspectionsDelete(cmd *cobra.Command, args []string) error {
	return runDelete(cmd, args, "Inspection", "inspections", idPath("/inspections/"), inspectionsDeleteDryRun, func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		return client.DeleteInspection(ctx, id)
	})
}

var inspectionsListCmd = &cobra.Command{
	RunE:  runInspectionsList,
	Short: "index",
	Use:   "list",
}

func runInspectionsList(cmd *cobra.Command, args []string) error {
	return runList(cmd, "inspections", "/inspections", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListInspections(ctx, nil)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var inspectionsShowCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runInspectionsShow,
	Short: "show",
	Use:   "show <id>",
}

func runInspectionsShow(cmd *cobra.Command, args []string) error {
	return runShow(cmd, args, "inspections", "GET", idPath("/inspections/"), func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.ShowInspection(ctx, id)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var inspectionsUpdateCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runInspectionsUpdate,
	Short: "update",
	Use:   "update <id>",
}

func runInspectionsUpdate(cmd *cobra.Command, args []string) error {
	return runUpdate(cmd, args, "inspections", idPath("/inspections/"), "Inspection updated.", func(id int) (any, error) {
		return nil, nil
	}, func(ctx context.Context, client *wenmar.Client, id int, body any) (any, error) {
		return nil, nil
	})
}

var inspectionsCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "inspections commands",
	Use:   "inspections",
}

func init() {
	inspectionsDeleteCmd.Flags().BoolVar(&inspectionsDeleteDryRun, "dry-run", false, "Preview what would be deleted without making an API call")
	inspectionsCmd.AddCommand(inspectionsCreateCmd, inspectionsDeleteCmd, inspectionsListCmd, inspectionsShowCmd, inspectionsUpdateCmd)
	rootCmd.AddCommand(inspectionsCmd)
}
