// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	"fmt"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var packagesCreateCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runPackagesCreate,
	Short: "duplicate",
	Use:   "create <id>",
}

func runPackagesCreate(cmd *cobra.Command, args []string) error {
	return runActionNoBody(cmd, args, "packages", "POST", func(a []string) string {
		return fmt.Sprintf("/packages/%s/duplicate", a[0])
	}, "Package create.", func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.CreatePackagesDuplicate(ctx, id)
		if err != nil {
			return nil, err
		}
		return resp.JSON201, nil
	})
}

var packagesCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "packages commands",
	Use:   "packages",
}

func init() {
	packagesCmd.AddCommand(packagesCreateCmd)
	rootCmd.AddCommand(packagesCmd)
}
