// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var servicecategoriesActive bool
var servicecategoriesDeleteDryRun bool
var servicecategoriesIcon string
var servicecategoriesName string
var servicecategoriesPosition int
var servicecategoriesServiceType string
var servicecategoriesCreateCmd = &cobra.Command{
	RunE:  runServicecategoriesCreate,
	Short: "Create a new service category",
	Use:   "create",
}

func runServicecategoriesCreate(cmd *cobra.Command, args []string) error {
	return runCreate(cmd, "servicecategories", "/service_categories", "Servicecategory created.", func() (any, error) {
		req := wenmar.CreateServiceCategoryRequest{ServiceCategory: struct {
			Icon        string `json:"icon"`
			Name        string `json:"name"`
			ServiceType string `json:"service_type"`
		}{
			Icon:        servicecategoriesIcon,
			Name:        servicecategoriesName,
			ServiceType: servicecategoriesServiceType,
		}}
		return req, nil
	}, func(ctx context.Context, client *wenmar.Client, body any) (any, error) {
		resp, err := client.CreateServiceCategory(ctx, body.(wenmar.CreateServiceCategoryRequest))
		if err != nil {
			return nil, err
		}
		return resp.JSON201, nil
	})
}

var servicecategoriesDeleteCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runServicecategoriesDelete,
	Short: "Delete a service category by ID",
	Use:   "delete <id>",
}

func runServicecategoriesDelete(cmd *cobra.Command, args []string) error {
	return runDelete(cmd, args, "Servicecategory", "servicecategories", idPath("/service_categories/"), servicecategoriesDeleteDryRun, func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		return client.DeleteServiceCategory(ctx, id)
	})
}

var servicecategoriesListCmd = &cobra.Command{
	Example: "wenmar servicecategories list\n",
	RunE:    runServicecategoriesList,
	Short:   "List all service categories",
	Use:     "list",
}

func runServicecategoriesList(cmd *cobra.Command, args []string) error {
	return runList(cmd, "servicecategories", "/service_categories", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListServiceCategories(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var servicecategoriesSeedDefaultsCmd = &cobra.Command{
	RunE:  runServicecategoriesSeedDefaults,
	Short: "Seed default service categories for the account",
	Use:   "seed-defaults",
}

func runServicecategoriesSeedDefaults(cmd *cobra.Command, args []string) error {
	return runSeedAction(cmd, "servicecategories", "/service_categories/seed_defaults", "Default service categories seeded.", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.SeedDefaultsServiceCategories(ctx, wenmar.SeedDefaultsServiceCategoriesRequest{})
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var servicecategoriesUpdateCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runServicecategoriesUpdate,
	Short: "Update a service category by ID",
	Use:   "update <id>",
}

func runServicecategoriesUpdate(cmd *cobra.Command, args []string) error {
	return runUpdate(cmd, args, "servicecategories", idPath("/service_categories/"), "Servicecategory updated.", func(id int) (any, error) {
		req := wenmar.UpdateServiceCategoryRequest{ServiceCategory: struct {
			Active   *bool   `json:"active,omitempty"`
			Name     *string `json:"name,omitempty"`
			Position *int    `json:"position,omitempty"`
		}{
			Active:   boolPtr(servicecategoriesActive),
			Name:     strPtr(servicecategoriesName),
			Position: intPtr(servicecategoriesPosition),
		}}
		return req, nil
	}, func(ctx context.Context, client *wenmar.Client, id int, body any) (any, error) {
		resp, err := client.UpdateServiceCategory(ctx, id, body.(wenmar.UpdateServiceCategoryRequest))
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var servicecategoriesCmd = &cobra.Command{
	Aliases: []string{"service-categories", "sc"},
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "Manage service categories",
	Use:   "servicecategories",
}

func init() {
	servicecategoriesCreateCmd.Flags().StringVar(&servicecategoriesIcon, "icon", "wrench", "Icon (wrench, disc, engine, etc.)")
	servicecategoriesCreateCmd.Flags().StringVar(&servicecategoriesName, "name", "", "Name (required)")
	servicecategoriesCreateCmd.MarkFlagRequired("name")
	servicecategoriesCreateCmd.Flags().StringVar(&servicecategoriesServiceType, "service-type", "maintenance", "Service type (maintenance, repair, diagnostic, recall, sublet)")
	servicecategoriesDeleteCmd.Flags().BoolVar(&servicecategoriesDeleteDryRun, "dry-run", false, "Preview what would be deleted without making an API call")
	servicecategoriesUpdateCmd.Flags().BoolVar(&servicecategoriesActive, "active", false, "Active")
	servicecategoriesUpdateCmd.Flags().StringVar(&servicecategoriesName, "name", "", "Name")
	servicecategoriesUpdateCmd.Flags().IntVar(&servicecategoriesPosition, "position", 0, "Position")
	servicecategoriesCmd.AddCommand(servicecategoriesCreateCmd, servicecategoriesDeleteCmd, servicecategoriesListCmd, servicecategoriesSeedDefaultsCmd, servicecategoriesUpdateCmd)
	rootCmd.AddCommand(servicecategoriesCmd)
}
