// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	"fmt"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var inspectionReportsDeleteDryRun bool
var inspectionReportsCreateCmd = &cobra.Command{
	RunE:  runInspectionReportsCreate,
	Short: "create",
	Use:   "create",
}

func runInspectionReportsCreate(cmd *cobra.Command, args []string) error {
	return runSeedAction(cmd, "inspection_reports", "/inspection_reports", "Inspection_report create.", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.CreateInspectionReport(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON201, nil
	})
}

var inspectionReportsDeleteCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runInspectionReportsDelete,
	Short: "destroy",
	Use:   "delete <id>",
}

func runInspectionReportsDelete(cmd *cobra.Command, args []string) error {
	return runDelete(cmd, args, "Inspection_report", "inspection_reports", idPath("/inspection_reports/"), inspectionReportsDeleteDryRun, func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		return client.DeleteInspectionReport(ctx, id)
	})
}

var inspectionReportsShowCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runInspectionReportsShow,
	Short: "show",
	Use:   "show <id>",
}

func runInspectionReportsShow(cmd *cobra.Command, args []string) error {
	return runShow(cmd, args, "inspection_reports", "GET", idPath("/inspection_reports/"), func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.ShowInspectionReport(ctx, id)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var inspectionReportsUpdateCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runInspectionReportsUpdate,
	Short: "complete",
	Use:   "update <id>",
}

func runInspectionReportsUpdate(cmd *cobra.Command, args []string) error {
	return runActionNoBody(cmd, args, "inspection_reports", "PATCH", func(a []string) string {
		return fmt.Sprintf("/inspection_reports/%s/complete", a[0])
	}, "Inspection_report update.", func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.CompleteInspectionReport(ctx, id)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var inspection_reportsCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "inspection_reports commands",
	Use:   "inspection_reports",
}

func init() {
	inspectionReportsDeleteCmd.Flags().BoolVar(&inspectionReportsDeleteDryRun, "dry-run", false, "Preview what would be deleted without making an API call")
	inspection_reportsCmd.AddCommand(inspectionReportsCreateCmd, inspectionReportsDeleteCmd, inspectionReportsShowCmd, inspectionReportsUpdateCmd)
	rootCmd.AddCommand(inspection_reportsCmd)
}
