// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var ordersDeleteDryRun bool
var ordersCreateCmd = &cobra.Command{
	RunE:  runOrdersCreate,
	Short: "create",
	Use:   "create",
}

func runOrdersCreate(cmd *cobra.Command, args []string) error {
	return runSeedAction(cmd, "orders", "/orders/purchase_orders", "Order create.", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.CreateOrdersPurchaseOrder(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON201, nil
	})
}

var ordersDeleteCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runOrdersDelete,
	Short: "destroy",
	Use:   "delete <id>",
}

func runOrdersDelete(cmd *cobra.Command, args []string) error {
	return runDelete(cmd, args, "Order", "orders", idPath("/orders/purchase_orders/"), ordersDeleteDryRun, func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		return client.DeleteOrdersPurchaseOrder(ctx, id)
	})
}

var ordersListCmd = &cobra.Command{
	RunE:  runOrdersList,
	Short: "index",
	Use:   "list",
}

func runOrdersList(cmd *cobra.Command, args []string) error {
	return runList(cmd, "orders", "/orders/purchase_orders", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListOrdersPurchaseOrders(ctx, nil)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var ordersShowCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runOrdersShow,
	Short: "show",
	Use:   "show <id>",
}

func runOrdersShow(cmd *cobra.Command, args []string) error {
	return runShow(cmd, args, "orders", "GET", idPath("/orders/purchase_orders/"), func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.ShowOrdersPurchaseOrder(ctx, id)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var ordersUpdateCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runOrdersUpdate,
	Short: "update",
	Use:   "update <id>",
}

func runOrdersUpdate(cmd *cobra.Command, args []string) error {
	return runUpdate(cmd, args, "orders", idPath("/orders/purchase_orders/"), "Order updated.", func(id int) (any, error) {
		return nil, nil
	}, func(ctx context.Context, client *wenmar.Client, id int, body any) (any, error) {
		return nil, nil
	})
}

var ordersCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "orders commands",
	Use:   "orders",
}

func init() {
	ordersDeleteCmd.Flags().BoolVar(&ordersDeleteDryRun, "dry-run", false, "Preview what would be deleted without making an API call")
	ordersCmd.AddCommand(ordersCreateCmd, ordersDeleteCmd, ordersListCmd, ordersShowCmd, ordersUpdateCmd)
	rootCmd.AddCommand(ordersCmd)
}
