// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var labelsCreateCmd = &cobra.Command{
	RunE:  runLabelsCreate,
	Short: "create",
	Use:   "create",
}

func runLabelsCreate(cmd *cobra.Command, args []string) error {
	return runSeedAction(cmd, "labels", "/labels", "Label create.", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.CreateLabel(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON201, nil
	})
}

var labelsListCmd = &cobra.Command{
	RunE:  runLabelsList,
	Short: "index",
	Use:   "list",
}

func runLabelsList(cmd *cobra.Command, args []string) error {
	return runList(cmd, "labels", "/labels", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListLabels(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var labelsUpdateCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runLabelsUpdate,
	Short: "update",
	Use:   "update <id>",
}

func runLabelsUpdate(cmd *cobra.Command, args []string) error {
	return runUpdate(cmd, args, "labels", idPath("/labels/"), "Label updated.", func(id int) (any, error) {
		return nil, nil
	}, func(ctx context.Context, client *wenmar.Client, id int, body any) (any, error) {
		return nil, nil
	})
}

var labelsCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "labels commands",
	Use:   "labels",
}

func init() {
	labelsCmd.AddCommand(labelsCreateCmd, labelsListCmd, labelsUpdateCmd)
	rootCmd.AddCommand(labelsCmd)
}
