// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var scanCreateCmd = &cobra.Command{
	RunE:  runScanCreate,
	Short: "lookup",
	Use:   "create",
}

func runScanCreate(cmd *cobra.Command, args []string) error {
	return runSeedAction(cmd, "scan", "/scan/lookups", "Scan create.", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.CreateScanLookup(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var scanCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "scan commands",
	Use:   "scan",
}

func init() {
	scanCmd.AddCommand(scanCreateCmd)
	rootCmd.AddCommand(scanCmd)
}
