// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var usersDeleteDryRun bool
var usersCreateCmd = &cobra.Command{
	RunE:  runUsersCreate,
	Short: "create",
	Use:   "create",
}

func runUsersCreate(cmd *cobra.Command, args []string) error {
	return runSeedAction(cmd, "users", "/users", "User create.", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.CreateUser(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON201, nil
	})
}

var usersDeleteCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runUsersDelete,
	Short: "destroy",
	Use:   "delete <id>",
}

func runUsersDelete(cmd *cobra.Command, args []string) error {
	return runDelete(cmd, args, "User", "users", idPath("/users/"), usersDeleteDryRun, func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		return client.DeleteUser(ctx, id)
	})
}

var usersListCmd = &cobra.Command{
	RunE:  runUsersList,
	Short: "index",
	Use:   "list",
}

func runUsersList(cmd *cobra.Command, args []string) error {
	return runList(cmd, "users", "/users", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListUsers(ctx, nil)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var usersShowCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runUsersShow,
	Short: "show",
	Use:   "show <id>",
}

func runUsersShow(cmd *cobra.Command, args []string) error {
	return runShow(cmd, args, "users", "GET", idPath("/users/"), func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.ShowUser(ctx, id)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var usersUpdateCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runUsersUpdate,
	Short: "update",
	Use:   "update <id>",
}

func runUsersUpdate(cmd *cobra.Command, args []string) error {
	return runUpdate(cmd, args, "users", idPath("/users/permission_groups/"), "User updated.", func(id int) (any, error) {
		return nil, nil
	}, func(ctx context.Context, client *wenmar.Client, id int, body any) (any, error) {
		return nil, nil
	})
}

var usersCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "users commands",
	Use:   "users",
}

func init() {
	usersDeleteCmd.Flags().BoolVar(&usersDeleteDryRun, "dry-run", false, "Preview what would be deleted without making an API call")
	usersCmd.AddCommand(usersCreateCmd, usersDeleteCmd, usersListCmd, usersShowCmd, usersUpdateCmd)
	rootCmd.AddCommand(usersCmd)
}
