// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var cashDrawerBannerUpdateCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runCashDrawerBannerUpdate,
	Short: "update",
	Use:   "update <id>",
}

func runCashDrawerBannerUpdate(cmd *cobra.Command, args []string) error {
	return runUpdate(cmd, args, "cash_drawer_banner", idPath("/cash_drawer_banner"), "Cash_drawer_banner updated.", func(id int) (any, error) {
		return nil, nil
	}, func(ctx context.Context, client *wenmar.Client, id int, body any) (any, error) {
		return nil, nil
	})
}

var cash_drawer_bannerCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "cash_drawer_banner commands",
	Use:   "cash_drawer_banner",
}

func init() {
	cash_drawer_bannerCmd.AddCommand(cashDrawerBannerUpdateCmd)
	rootCmd.AddCommand(cash_drawer_bannerCmd)
}
