// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	"fmt"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var servicecategoriesDeleteDryRun bool
var servicecategoriesIcon string
var servicecategoriesName string
var servicecategoriesServiceType string
var servicecategoriesCreateCmd = &cobra.Command{
	RunE:  runServicecategoriesCreate,
	Short: "Create a new service category",
	Use:   "create",
}

func runServicecategoriesCreate(cmd *cobra.Command, args []string) error {
	return runCreate(cmd, "servicecategories", "/service_categories", "Servicecategory created.", func() (any, error) {
		req := wenmar.CreateServiceCategoryRequest{ServiceCategory: struct {
			Icon        string `json:"icon"`
			Name        string `json:"name"`
			ServiceType string `json:"service_type"`
		}{
			Icon:        servicecategoriesIcon,
			Name:        servicecategoriesName,
			ServiceType: servicecategoriesServiceType,
		}}
		return req, nil
	}, func(ctx context.Context, client *wenmar.Client, body any) (any, error) {
		resp, err := client.CreateServiceCategory(ctx, body.(wenmar.CreateServiceCategoryRequest))
		if err != nil {
			return nil, err
		}
		return resp.JSON201, nil
	})
}

var servicecategoriesDeactivateCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runServicecategoriesDeactivate,
	Short: "Deactivate a service category by ID",
	Use:   "deactivate <id>",
}

func runServicecategoriesDeactivate(cmd *cobra.Command, args []string) error {
	return runActionNoBody(cmd, args, "servicecategories", "PATCH", func(a []string) string {
		return fmt.Sprintf("/service_categories/%s/deactivate", a[0])
	}, "Servicecategory deactivate.", func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.DeactivateServiceCategory(ctx, id, wenmar.DeactivateServiceCategoryRequest{})
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var servicecategoriesDeleteCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runServicecategoriesDelete,
	Short: "Delete a service category by ID",
	Use:   "delete <id>",
}

func runServicecategoriesDelete(cmd *cobra.Command, args []string) error {
	return runDelete(cmd, args, "Servicecategory", "servicecategories", idPath("/service_categories/"), servicecategoriesDeleteDryRun, func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		return client.DeleteServiceCategory(ctx, id)
	})
}

var servicecategoriesListCmd = &cobra.Command{
	RunE:  runServicecategoriesList,
	Short: "List all service categories",
	Use:   "list",
}

func runServicecategoriesList(cmd *cobra.Command, args []string) error {
	return runList(cmd, "servicecategories", "/service_categories", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListServiceCategories(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var servicecategoriesMoveDownCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runServicecategoriesMoveDown,
	Short: "Move a service category down one position",
	Use:   "move-down <id>",
}

func runServicecategoriesMoveDown(cmd *cobra.Command, args []string) error {
	return runActionNoBody(cmd, args, "servicecategories", "PATCH", func(a []string) string {
		return fmt.Sprintf("/service_categories/%s/move_down", a[0])
	}, "Servicecategory move-down.", func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.MoveDownServiceCategory(ctx, id, wenmar.MoveDownServiceCategoryRequest{})
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var servicecategoriesMoveUpCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runServicecategoriesMoveUp,
	Short: "Move a service category up one position",
	Use:   "move-up <id>",
}

func runServicecategoriesMoveUp(cmd *cobra.Command, args []string) error {
	return runActionNoBody(cmd, args, "servicecategories", "PATCH", func(a []string) string {
		return fmt.Sprintf("/service_categories/%s/move_up", a[0])
	}, "Servicecategory move-up.", func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.MoveUpServiceCategory(ctx, id, wenmar.MoveUpServiceCategoryRequest{})
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var servicecategoriesReactivateCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runServicecategoriesReactivate,
	Short: "Reactivate a service category by ID",
	Use:   "reactivate <id>",
}

func runServicecategoriesReactivate(cmd *cobra.Command, args []string) error {
	return runActionNoBody(cmd, args, "servicecategories", "PATCH", func(a []string) string {
		return fmt.Sprintf("/service_categories/%s/reactivate", a[0])
	}, "Servicecategory reactivate.", func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.ReactivateServiceCategory(ctx, id, wenmar.ReactivateServiceCategoryRequest{})
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var servicecategoriesSeedDefaultsCmd = &cobra.Command{
	RunE:  runServicecategoriesSeedDefaults,
	Short: "Seed default service categories for the account",
	Use:   "seed-defaults",
}

func runServicecategoriesSeedDefaults(cmd *cobra.Command, args []string) error {
	return runSeedAction(cmd, "servicecategories", "/service_categories/seed_defaults", "Default service categories seeded.", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.SeedDefaultsServiceCategories(ctx, wenmar.SeedDefaultsServiceCategoriesRequest{})
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var servicecategoriesUpdateCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runServicecategoriesUpdate,
	Short: "Update a service category by ID",
	Use:   "update <id>",
}

func runServicecategoriesUpdate(cmd *cobra.Command, args []string) error {
	return runUpdate(cmd, args, "servicecategories", idPath("/service_categories/"), "Servicecategory updated.", func(id int) (any, error) {
		req := wenmar.UpdateServiceCategoryRequest{ServiceCategory: struct {
			Name string `json:"name"`
		}{Name: servicecategoriesName}}
		return req, nil
	}, func(ctx context.Context, client *wenmar.Client, id int, body any) (any, error) {
		resp, err := client.UpdateServiceCategory(ctx, id, body.(wenmar.UpdateServiceCategoryRequest))
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var servicecategoriesCmd = &cobra.Command{
	Aliases: []string{"service-categories", "sc"},
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "Manage service categories",
	Use:   "servicecategories",
}

func init() {
	servicecategoriesCreateCmd.Flags().StringVar(&servicecategoriesIcon, "icon", "wrench", "Icon (wrench, disc, engine, etc.)")
	servicecategoriesCreateCmd.Flags().StringVar(&servicecategoriesName, "name", "", "Name (required)")
	servicecategoriesCreateCmd.MarkFlagRequired("name")
	servicecategoriesCreateCmd.Flags().StringVar(&servicecategoriesServiceType, "service-type", "maintenance", "Service type (maintenance, repair, diagnostic, recall, sublet)")
	servicecategoriesDeleteCmd.Flags().BoolVar(&servicecategoriesDeleteDryRun, "dry-run", false, "Preview what would be deleted without making an API call")
	servicecategoriesUpdateCmd.Flags().StringVar(&servicecategoriesName, "name", "", "Name (required)")
	servicecategoriesUpdateCmd.MarkFlagRequired("name")
	servicecategoriesCmd.AddCommand(servicecategoriesCreateCmd, servicecategoriesDeactivateCmd, servicecategoriesDeleteCmd, servicecategoriesListCmd, servicecategoriesMoveDownCmd, servicecategoriesMoveUpCmd, servicecategoriesReactivateCmd, servicecategoriesSeedDefaultsCmd, servicecategoriesUpdateCmd)
	rootCmd.AddCommand(servicecategoriesCmd)
}
