// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var shopDiscountsDeleteDryRun bool
var shopDiscountsCreateCmd = &cobra.Command{
	RunE:  runShopDiscountsCreate,
	Short: "create",
	Use:   "create",
}

func runShopDiscountsCreate(cmd *cobra.Command, args []string) error {
	return runSeedAction(cmd, "shop_discounts", "/shop_discounts", "Shop_discount create.", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.CreateShopDiscount(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON201, nil
	})
}

var shopDiscountsDeleteCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runShopDiscountsDelete,
	Short: "destroy",
	Use:   "delete <id>",
}

func runShopDiscountsDelete(cmd *cobra.Command, args []string) error {
	return runDelete(cmd, args, "Shop_discount", "shop_discounts", idPath("/shop_discounts/"), shopDiscountsDeleteDryRun, func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		return client.DeleteShopDiscount(ctx, id)
	})
}

var shopDiscountsListCmd = &cobra.Command{
	RunE:  runShopDiscountsList,
	Short: "index",
	Use:   "list",
}

func runShopDiscountsList(cmd *cobra.Command, args []string) error {
	return runList(cmd, "shop_discounts", "/shop_discounts", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListShopDiscounts(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var shopDiscountsUpdateCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runShopDiscountsUpdate,
	Short: "update",
	Use:   "update <id>",
}

func runShopDiscountsUpdate(cmd *cobra.Command, args []string) error {
	return runUpdate(cmd, args, "shop_discounts", idPath("/shop_discounts/"), "Shop_discount updated.", func(id int) (any, error) {
		return nil, nil
	}, func(ctx context.Context, client *wenmar.Client, id int, body any) (any, error) {
		return nil, nil
	})
}

var shop_discountsCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "shop_discounts commands",
	Use:   "shop_discounts",
}

func init() {
	shopDiscountsDeleteCmd.Flags().BoolVar(&shopDiscountsDeleteDryRun, "dry-run", false, "Preview what would be deleted without making an API call")
	shop_discountsCmd.AddCommand(shopDiscountsCreateCmd, shopDiscountsDeleteCmd, shopDiscountsListCmd, shopDiscountsUpdateCmd)
	rootCmd.AddCommand(shop_discountsCmd)
}
