// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var settingsDeleteDryRun bool
var settingsDeleteCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runSettingsDelete,
	Short: "destroy",
	Use:   "delete <id>",
}

func runSettingsDelete(cmd *cobra.Command, args []string) error {
	return runDelete(cmd, args, "Setting", "settings", idPath("/settings/labor_templates/"), settingsDeleteDryRun, func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		return client.DeleteSettingsLaborTemplate(ctx, id)
	})
}

var settingsListCmd = &cobra.Command{
	RunE:  runSettingsList,
	Short: "show",
	Use:   "list",
}

func runSettingsList(cmd *cobra.Command, args []string) error {
	return runList(cmd, "settings", "/settings/account", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListSettingsAccount(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var settingsUpdateCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runSettingsUpdate,
	Short: "update",
	Use:   "update <id>",
}

func runSettingsUpdate(cmd *cobra.Command, args []string) error {
	return runUpdate(cmd, args, "settings", idPath("/settings/account"), "Setting updated.", func(id int) (any, error) {
		return nil, nil
	}, func(ctx context.Context, client *wenmar.Client, id int, body any) (any, error) {
		return nil, nil
	})
}

var settingsCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "settings commands",
	Use:   "settings",
}

func init() {
	settingsDeleteCmd.Flags().BoolVar(&settingsDeleteDryRun, "dry-run", false, "Preview what would be deleted without making an API call")
	settingsCmd.AddCommand(settingsDeleteCmd, settingsListCmd, settingsUpdateCmd)
	rootCmd.AddCommand(settingsCmd)
}
