// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var catalogCleanupsCatalogCleanupId int
var catalogCleanupsCreateCmd = &cobra.Command{
	RunE:  runCatalogCleanupsCreate,
	Short: "create",
	Use:   "create",
}

func runCatalogCleanupsCreate(cmd *cobra.Command, args []string) error {
	return runSeedAction(cmd, "catalog_cleanups", "/catalog_cleanups/{catalog_cleanup_id}/applications", "Catalog_cleanup create.", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.CreateCatalogCleanupsApplication(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var catalog_cleanupsCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "catalog_cleanups commands",
	Use:   "catalog_cleanups",
}

func init() {
	catalogCleanupsCreateCmd.Flags().IntVar(&catalogCleanupsCatalogCleanupId, "catalog-cleanup-id", 0, "Catalog Cleanup ID (required)")
	catalogCleanupsCreateCmd.MarkFlagRequired("catalog-cleanup-id")
	catalog_cleanupsCmd.AddCommand(catalogCleanupsCreateCmd)
	rootCmd.AddCommand(catalog_cleanupsCmd)
}
