// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var partsMatricesDeleteDryRun bool
var partsMatricesCreateCmd = &cobra.Command{
	RunE:  runPartsMatricesCreate,
	Short: "create",
	Use:   "create",
}

func runPartsMatricesCreate(cmd *cobra.Command, args []string) error {
	return runSeedAction(cmd, "parts_matrices", "/parts_matrices", "Parts_matrice create.", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.CreatePartsMatrice(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON201, nil
	})
}

var partsMatricesDeleteCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runPartsMatricesDelete,
	Short: "destroy",
	Use:   "delete <id>",
}

func runPartsMatricesDelete(cmd *cobra.Command, args []string) error {
	return runDelete(cmd, args, "Parts_matrice", "parts_matrices", idPath("/parts_matrices/"), partsMatricesDeleteDryRun, func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		return client.DeletePartsMatrice(ctx, id)
	})
}

var partsMatricesListCmd = &cobra.Command{
	RunE:  runPartsMatricesList,
	Short: "index",
	Use:   "list",
}

func runPartsMatricesList(cmd *cobra.Command, args []string) error {
	return runList(cmd, "parts_matrices", "/parts_matrices", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListPartsMatrices(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var partsMatricesUpdateCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runPartsMatricesUpdate,
	Short: "update",
	Use:   "update <id>",
}

func runPartsMatricesUpdate(cmd *cobra.Command, args []string) error {
	return runUpdate(cmd, args, "parts_matrices", idPath("/parts_matrices/"), "Parts_matrice updated.", func(id int) (any, error) {
		return nil, nil
	}, func(ctx context.Context, client *wenmar.Client, id int, body any) (any, error) {
		return nil, nil
	})
}

var parts_matricesCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "parts_matrices commands",
	Use:   "parts_matrices",
}

func init() {
	partsMatricesDeleteCmd.Flags().BoolVar(&partsMatricesDeleteDryRun, "dry-run", false, "Preview what would be deleted without making an API call")
	parts_matricesCmd.AddCommand(partsMatricesCreateCmd, partsMatricesDeleteCmd, partsMatricesListCmd, partsMatricesUpdateCmd)
	rootCmd.AddCommand(parts_matricesCmd)
}
