// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	"fmt"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var workOrdersDeleteDryRun bool
var workOrdersWorkOrderId int
var workOrdersCreateCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runWorkOrdersCreate,
	Short: "create",
	Use:   "create <id>",
}

func runWorkOrdersCreate(cmd *cobra.Command, args []string) error {
	return runActionNoBody(cmd, args, "work_orders", "POST", func(a []string) string {
		return fmt.Sprintf("/work_orders/%s/courtesy_car_assignment", a[0])
	}, "Work order create.", func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.CreateWorkOrdersCourtesyCarAssignment(ctx, id)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var workOrdersDeleteCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runWorkOrdersDelete,
	Short: "destroy",
	Use:   "delete <id>",
}

func runWorkOrdersDelete(cmd *cobra.Command, args []string) error {
	return runDelete(cmd, args, "Work order", "work_orders", func(a []string) string {
		return fmt.Sprintf("/work_orders/%s/courtesy_car_assignment", a[0])
	}, workOrdersDeleteDryRun, func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		return client.DeleteWorkOrdersCourtesyCarAssignment(ctx, id)
	})
}

var workOrdersListCmd = &cobra.Command{
	RunE:  runWorkOrdersList,
	Short: "index",
	Use:   "list",
}

func runWorkOrdersList(cmd *cobra.Command, args []string) error {
	return runList(cmd, "work_orders", fmt.Sprintf("/work_orders/%d/concerns", workOrdersWorkOrderId), func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListWorkOrdersConcerns(ctx, workOrdersWorkOrderId)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var workOrdersShowCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runWorkOrdersShow,
	Short: "adjust_time",
	Use:   "show <id>",
}

func runWorkOrdersShow(cmd *cobra.Command, args []string) error {
	return runShow(cmd, args, "work_orders", "GET", func(a []string) string {
		return fmt.Sprintf("/work_orders/%d/services/%s/adjust_time", a[0], workOrdersWorkOrderId)
	}, func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.ListWorkOrdersServicesAdjustTime(ctx, workOrdersWorkOrderId, id)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var workOrdersUpdateCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runWorkOrdersUpdate,
	Short: "update",
	Use:   "update <id>",
}

func runWorkOrdersUpdate(cmd *cobra.Command, args []string) error {
	return runActionNoBody(cmd, args, "work_orders", "PATCH", func(a []string) string {
		return fmt.Sprintf("/work_orders/%s/courtesy_car_assignment", a[0])
	}, "Work order update.", func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.UpdateWorkOrdersCourtesyCarAssignment(ctx, id)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var work_ordersCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "work_orders commands",
	Use:   "work_orders",
}

func init() {
	workOrdersDeleteCmd.Flags().BoolVar(&workOrdersDeleteDryRun, "dry-run", false, "Preview what would be deleted without making an API call")
	workOrdersListCmd.Flags().IntVar(&workOrdersWorkOrderId, "work-order-id", 0, "Work Order ID (required)")
	workOrdersListCmd.MarkFlagRequired("work-order-id")
	workOrdersShowCmd.Flags().IntVar(&workOrdersWorkOrderId, "work-order-id", 0, "Work Order ID (required)")
	workOrdersShowCmd.MarkFlagRequired("work-order-id")
	work_ordersCmd.AddCommand(workOrdersCreateCmd, workOrdersDeleteCmd, workOrdersListCmd, workOrdersShowCmd, workOrdersUpdateCmd)
	rootCmd.AddCommand(work_ordersCmd)
}
