// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var voiceCommandsDeleteDryRun bool
var voiceCommandsDeleteCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runVoiceCommandsDelete,
	Short: "destroy",
	Use:   "delete <id>",
}

func runVoiceCommandsDelete(cmd *cobra.Command, args []string) error {
	return runDelete(cmd, args, "Voice_command", "voice_commands", idPath("/voice_commands/"), voiceCommandsDeleteDryRun, func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		return client.DeleteVoiceCommand(ctx, id)
	})
}

var voice_commandsCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "voice_commands commands",
	Use:   "voice_commands",
}

func init() {
	voiceCommandsDeleteCmd.Flags().BoolVar(&voiceCommandsDeleteDryRun, "dry-run", false, "Preview what would be deleted without making an API call")
	voice_commandsCmd.AddCommand(voiceCommandsDeleteCmd)
	rootCmd.AddCommand(voice_commandsCmd)
}
