// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var shopFeesDeleteDryRun bool
var shopFeesCreateCmd = &cobra.Command{
	RunE:  runShopFeesCreate,
	Short: "create",
	Use:   "create",
}

func runShopFeesCreate(cmd *cobra.Command, args []string) error {
	return runSeedAction(cmd, "shop_fees", "/shop_fees", "Shop_fee create.", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.CreateShopFee(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON201, nil
	})
}

var shopFeesDeleteCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runShopFeesDelete,
	Short: "destroy",
	Use:   "delete <id>",
}

func runShopFeesDelete(cmd *cobra.Command, args []string) error {
	return runDelete(cmd, args, "Shop_fee", "shop_fees", idPath("/shop_fees/"), shopFeesDeleteDryRun, func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		return client.DeleteShopFee(ctx, id)
	})
}

var shopFeesListCmd = &cobra.Command{
	RunE:  runShopFeesList,
	Short: "index",
	Use:   "list",
}

func runShopFeesList(cmd *cobra.Command, args []string) error {
	return runList(cmd, "shop_fees", "/shop_fees", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListShopFees(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var shopFeesUpdateCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runShopFeesUpdate,
	Short: "update",
	Use:   "update <id>",
}

func runShopFeesUpdate(cmd *cobra.Command, args []string) error {
	return runUpdate(cmd, args, "shop_fees", idPath("/shop_fees/"), "Shop_fee updated.", func(id int) (any, error) {
		return nil, nil
	}, func(ctx context.Context, client *wenmar.Client, id int, body any) (any, error) {
		return nil, nil
	})
}

var shop_feesCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "shop_fees commands",
	Use:   "shop_fees",
}

func init() {
	shopFeesDeleteCmd.Flags().BoolVar(&shopFeesDeleteDryRun, "dry-run", false, "Preview what would be deleted without making an API call")
	shop_feesCmd.AddCommand(shopFeesCreateCmd, shopFeesDeleteCmd, shopFeesListCmd, shopFeesUpdateCmd)
	rootCmd.AddCommand(shop_feesCmd)
}
