// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var laborRatesDeleteDryRun bool
var laborRatesCreateCmd = &cobra.Command{
	RunE:  runLaborRatesCreate,
	Short: "create",
	Use:   "create",
}

func runLaborRatesCreate(cmd *cobra.Command, args []string) error {
	return runSeedAction(cmd, "labor_rates", "/labor_rates", "Labor_rate create.", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.CreateLaborRate(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON201, nil
	})
}

var laborRatesDeleteCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runLaborRatesDelete,
	Short: "destroy",
	Use:   "delete <id>",
}

func runLaborRatesDelete(cmd *cobra.Command, args []string) error {
	return runDelete(cmd, args, "Labor_rate", "labor_rates", idPath("/labor_rates/"), laborRatesDeleteDryRun, func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		return client.DeleteLaborRate(ctx, id)
	})
}

var laborRatesListCmd = &cobra.Command{
	RunE:  runLaborRatesList,
	Short: "index",
	Use:   "list",
}

func runLaborRatesList(cmd *cobra.Command, args []string) error {
	return runList(cmd, "labor_rates", "/labor_rates", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListLaborRates(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var laborRatesUpdateCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runLaborRatesUpdate,
	Short: "update",
	Use:   "update <id>",
}

func runLaborRatesUpdate(cmd *cobra.Command, args []string) error {
	return runUpdate(cmd, args, "labor_rates", idPath("/labor_rates/"), "Labor_rate updated.", func(id int) (any, error) {
		return nil, nil
	}, func(ctx context.Context, client *wenmar.Client, id int, body any) (any, error) {
		return nil, nil
	})
}

var labor_ratesCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "labor_rates commands",
	Use:   "labor_rates",
}

func init() {
	laborRatesDeleteCmd.Flags().BoolVar(&laborRatesDeleteDryRun, "dry-run", false, "Preview what would be deleted without making an API call")
	labor_ratesCmd.AddCommand(laborRatesCreateCmd, laborRatesDeleteCmd, laborRatesListCmd, laborRatesUpdateCmd)
	rootCmd.AddCommand(labor_ratesCmd)
}
