// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	"fmt"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var conversationsConversationId int
var conversationsCreateCmd = &cobra.Command{
	RunE:  runConversationsCreate,
	Short: "bulk_mark_read",
	Use:   "create",
}

func runConversationsCreate(cmd *cobra.Command, args []string) error {
	return runSeedAction(cmd, "conversations", "/conversations/bulk_mark_read", "Conversation create.", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.CreateConversationsBulkMarkRead(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var conversationsListCmd = &cobra.Command{
	RunE:  runConversationsList,
	Short: "index",
	Use:   "list",
}

func runConversationsList(cmd *cobra.Command, args []string) error {
	return runList(cmd, "conversations", fmt.Sprintf("/conversations/%d/messages", conversationsConversationId), func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListConversationsMessages(ctx, conversationsConversationId)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var conversationsCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "conversations commands",
	Use:   "conversations",
}

func init() {
	conversationsListCmd.Flags().IntVar(&conversationsConversationId, "conversation-id", 0, "Conversation ID (required)")
	conversationsListCmd.MarkFlagRequired("conversation-id")
	conversationsCmd.AddCommand(conversationsCreateCmd, conversationsListCmd)
	rootCmd.AddCommand(conversationsCmd)
}
