// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var tireStorageSlotsTireStorageSlotId int
var tireStorageSlotsCreateCmd = &cobra.Command{
	RunE:  runTireStorageSlotsCreate,
	Short: "create",
	Use:   "create",
}

func runTireStorageSlotsCreate(cmd *cobra.Command, args []string) error {
	return runSeedAction(cmd, "tire_storage_slots", "/tire_storage_slots/{tire_storage_slot_id}/check_outs", "Tire_storage_slot create.", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.CreateTireStorageSlotsCheckOut(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var tire_storage_slotsCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "tire_storage_slots commands",
	Use:   "tire_storage_slots",
}

func init() {
	tireStorageSlotsCreateCmd.Flags().IntVar(&tireStorageSlotsTireStorageSlotId, "tire-storage-slot-id", 0, "Tire Storage Slot ID (required)")
	tireStorageSlotsCreateCmd.MarkFlagRequired("tire-storage-slot-id")
	tire_storage_slotsCmd.AddCommand(tireStorageSlotsCreateCmd)
	rootCmd.AddCommand(tire_storage_slotsCmd)
}
