// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var reportsListCmd = &cobra.Command{
	RunE:  runReportsList,
	Short: "show",
	Use:   "list",
}

func runReportsList(cmd *cobra.Command, args []string) error {
	return runList(cmd, "reports", "/reports/accounting", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListReportsAccounting(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var reportsCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "reports commands",
	Use:   "reports",
}

func init() {
	reportsCmd.AddCommand(reportsListCmd)
	rootCmd.AddCommand(reportsCmd)
}
