// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var laborMatricesDeleteDryRun bool
var laborMatricesCreateCmd = &cobra.Command{
	RunE:  runLaborMatricesCreate,
	Short: "create",
	Use:   "create",
}

func runLaborMatricesCreate(cmd *cobra.Command, args []string) error {
	return runSeedAction(cmd, "labor_matrices", "/labor_matrices", "Labor_matrice create.", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.CreateLaborMatrice(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON201, nil
	})
}

var laborMatricesDeleteCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runLaborMatricesDelete,
	Short: "destroy",
	Use:   "delete <id>",
}

func runLaborMatricesDelete(cmd *cobra.Command, args []string) error {
	return runDelete(cmd, args, "Labor_matrice", "labor_matrices", idPath("/labor_matrices/"), laborMatricesDeleteDryRun, func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		return client.DeleteLaborMatrice(ctx, id)
	})
}

var laborMatricesListCmd = &cobra.Command{
	RunE:  runLaborMatricesList,
	Short: "index",
	Use:   "list",
}

func runLaborMatricesList(cmd *cobra.Command, args []string) error {
	return runList(cmd, "labor_matrices", "/labor_matrices", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListLaborMatrices(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var laborMatricesUpdateCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runLaborMatricesUpdate,
	Short: "update",
	Use:   "update <id>",
}

func runLaborMatricesUpdate(cmd *cobra.Command, args []string) error {
	return runUpdate(cmd, args, "labor_matrices", idPath("/labor_matrices/"), "Labor_matrice updated.", func(id int) (any, error) {
		return nil, nil
	}, func(ctx context.Context, client *wenmar.Client, id int, body any) (any, error) {
		return nil, nil
	})
}

var labor_matricesCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "labor_matrices commands",
	Use:   "labor_matrices",
}

func init() {
	laborMatricesDeleteCmd.Flags().BoolVar(&laborMatricesDeleteDryRun, "dry-run", false, "Preview what would be deleted without making an API call")
	labor_matricesCmd.AddCommand(laborMatricesCreateCmd, laborMatricesDeleteCmd, laborMatricesListCmd, laborMatricesUpdateCmd)
	rootCmd.AddCommand(labor_matricesCmd)
}
