// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var campaignsCreateCmd = &cobra.Command{
	RunE:  runCampaignsCreate,
	Short: "create",
	Use:   "create",
}

func runCampaignsCreate(cmd *cobra.Command, args []string) error {
	return runSeedAction(cmd, "campaigns", "/campaigns", "Campaign create.", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.CreateCampaign(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON201, nil
	})
}

var campaignsListCmd = &cobra.Command{
	RunE:  runCampaignsList,
	Short: "index",
	Use:   "list",
}

func runCampaignsList(cmd *cobra.Command, args []string) error {
	return runList(cmd, "campaigns", "/campaigns", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListCampaigns(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var campaignsShowCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runCampaignsShow,
	Short: "show",
	Use:   "show <id>",
}

func runCampaignsShow(cmd *cobra.Command, args []string) error {
	return runShow(cmd, args, "campaigns", "GET", idPath("/campaigns/"), func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.ShowCampaign(ctx, id)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var campaignsCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "campaigns commands",
	Use:   "campaigns",
}

func init() {
	campaignsCmd.AddCommand(campaignsCreateCmd, campaignsListCmd, campaignsShowCmd)
	rootCmd.AddCommand(campaignsCmd)
}
