// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var accountShowCmd = &cobra.Command{
	Example: "wenmar account show\n",
	RunE:    runAccountShow,
	Short:   "Show account details",
	Use:     "show",
}

func runAccountShow(cmd *cobra.Command, args []string) error {
	return runList(cmd, "account", "/account", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListAccount(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var accountCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "Show the current account",
	Use:   "account",
}

func init() {
	accountCmd.AddCommand(accountShowCmd)
	rootCmd.AddCommand(accountCmd)
}
