// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var recentSearchesDeleteDryRun bool
var recentSearchesCreateCmd = &cobra.Command{
	RunE:  runRecentSearchesCreate,
	Short: "create",
	Use:   "create",
}

func runRecentSearchesCreate(cmd *cobra.Command, args []string) error {
	return runSeedAction(cmd, "recent_searches", "/recent_searches", "Recent_searche create.", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.CreateRecentSearche(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var recentSearchesDeleteCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runRecentSearchesDelete,
	Short: "clear",
	Use:   "delete <id>",
}

func runRecentSearchesDelete(cmd *cobra.Command, args []string) error {
	return runDelete(cmd, args, "Recent_searche", "recent_searches", idPath("/recent_searches/clear"), recentSearchesDeleteDryRun, func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		return client.DeleteRecentSearchesClear(ctx, id)
	})
}

var recentSearchesListCmd = &cobra.Command{
	RunE:  runRecentSearchesList,
	Short: "index",
	Use:   "list",
}

func runRecentSearchesList(cmd *cobra.Command, args []string) error {
	return runList(cmd, "recent_searches", "/recent_searches", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListRecentSearches(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var recent_searchesCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "recent_searches commands",
	Use:   "recent_searches",
}

func init() {
	recentSearchesDeleteCmd.Flags().BoolVar(&recentSearchesDeleteDryRun, "dry-run", false, "Preview what would be deleted without making an API call")
	recent_searchesCmd.AddCommand(recentSearchesCreateCmd, recentSearchesDeleteCmd, recentSearchesListCmd)
	rootCmd.AddCommand(recent_searchesCmd)
}
