// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	"fmt"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var customersEmail string
var customersFirstName string
var customersHasBalance bool
var customersHasVehicle bool
var customersLastName string
var customersLastVisitMonths int
var customersListAll bool
var customersPage int
var customersPerPage int
var customersPhone int
var customersQ string
var customersSourceCustomerId int
var customersStatus string
var customersTagIds []int
var customersType string
var customersArchiveCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runCustomersArchive,
	Short: "Archive a customer (hidden from active lists, retained for history)",
	Use:   "archive <id>",
}

func runCustomersArchive(cmd *cobra.Command, args []string) error {
	return runActionNoBody(cmd, args, "customers", "PATCH", func(a []string) string {
		return fmt.Sprintf("/customers/%s/archive", a[0])
	}, "Customer archive.", func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.ArchiveCustomer(ctx, id)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var customersCreateCmd = &cobra.Command{
	RunE:  runCustomersCreate,
	Short: "create",
	Use:   "create",
}

func runCustomersCreate(cmd *cobra.Command, args []string) error {
	return runSeedAction(cmd, "customers", "/customers/export", "Customer create.", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.CreateCustomersExport(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var customersDuplicatesCmd = &cobra.Command{
	RunE:  runCustomersDuplicates,
	Short: "Check for duplicate customers",
	Use:   "duplicates",
}

func runCustomersDuplicates(cmd *cobra.Command, args []string) error {
	return runList(cmd, "customers", "/customers/check_duplicate", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.CheckCustomerDuplicate(ctx, &wenmar.CheckCustomerDuplicateParams{
			Email:     strPtr(customersEmail),
			FirstName: strPtr(customersFirstName),
			LastName:  strPtr(customersLastName),
			Phone:     intPtr(customersPhone),
		})
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var customersListCmd = &cobra.Command{
	Example: "wenmar customers list\nwenmar customers list --query \"jane\" --all\nwenmar customers list --agent | head -20\n",
	RunE:    runCustomersList,
	Short:   "List all customers, paginated via the Link header",
	Use:     "list",
}

func runCustomersList(cmd *cobra.Command, args []string) error {
	return runListPaginatedWithAll(cmd, "customers", "/customers", customersListAll, func(ctx context.Context, client *wenmar.Client) (any, *wenmar.Paginator, error) {
		if customersListHasFilters() {
			resp, err := client.ListCustomers(ctx, &wenmar.ListCustomersParams{
				HasBalance:      boolPtr(customersHasBalance),
				HasVehicle:      boolPtr(customersHasVehicle),
				LastVisitMonths: intPtr(customersLastVisitMonths),
				Page:            intPtr(customersPage),
				PerPage:         intPtr(customersPerPage),
				Q:               strPtr(customersQ),
				Status:          strPtr(customersStatus),
				TagIds:          intSliceToStrPtr(customersTagIds),
				Type:            strPtr(customersType),
			})
			if err != nil {
				return nil, nil, err
			}
			return resp.JSON200, client.PaginatorFromResponse(resp.HTTPResponse), nil
		} else {
			resp, err := client.ListCustomers(ctx, nil)
			if err != nil {
				return nil, nil, err
			}
			return resp.JSON200, client.PaginatorFromResponse(resp.HTTPResponse), nil
		}
	})
}

var customersLookupCmd = &cobra.Command{
	Args:    cobra.ExactArgs(1),
	Example: "wenmar customers lookup \"jane doe\"\n",
	RunE:    runCustomersLookup,
	Short:   "Search customers by name/email/phone",
	Use:     "lookup <string>",
}

func runCustomersLookup(cmd *cobra.Command, args []string) error {
	return runList(cmd, "customers", "/customers/lookup", func(ctx context.Context, client *wenmar.Client) (any, error) {
		query := args[0]
		resp, err := client.LookupCustomer(ctx, &wenmar.LookupCustomerParams{Query: strPtr(query)})
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var customersMergeCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runCustomersMerge,
	Short: "Merge a source customer into this keeper",
	Use:   "merge <id>",
}

func runCustomersMerge(cmd *cobra.Command, args []string) error {
	return runAction(cmd, args, "customers", "POST", func(a []string) string {
		return fmt.Sprintf("/customers/%s/merges", a[0])
	}, "Customer action completed.", func(id int) (any, error) {
		req := wenmar.MergeCustomerRequest{SourceCustomerId: customersSourceCustomerId}
		return req, nil
	}, func(ctx context.Context, client *wenmar.Client, id int, body any) (any, error) {
		resp, err := client.MergeCustomer(ctx, id, body.(wenmar.MergeCustomerRequest))
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var customersRestoreCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runCustomersRestore,
	Short: "Restore a customer to active (from trashed or archived)",
	Use:   "restore <id>",
}

func runCustomersRestore(cmd *cobra.Command, args []string) error {
	return runActionNoBody(cmd, args, "customers", "PATCH", func(a []string) string {
		return fmt.Sprintf("/customers/%s/restore", a[0])
	}, "Customer restore.", func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.RestoreCustomer(ctx, id)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var customersShowCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runCustomersShow,
	Short: "download",
	Use:   "show <id>",
}

func runCustomersShow(cmd *cobra.Command, args []string) error {
	return runShow(cmd, args, "customers", "GET", func(a []string) string {
		return fmt.Sprintf("/customers/export/%s/download", a[0])
	}, func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.ListCustomersExportDownload(ctx, id)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var customersTrashCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runCustomersTrash,
	Short: "Soft-delete a customer (status: trashed, purgeable after 30 days)",
	Use:   "trash <id>",
}

func runCustomersTrash(cmd *cobra.Command, args []string) error {
	return runActionNoBody(cmd, args, "customers", "PATCH", func(a []string) string {
		return fmt.Sprintf("/customers/%s/trash", a[0])
	}, "Customer trash.", func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.TrashCustomer(ctx, id)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var customersVehiclesCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runCustomersVehicles,
	Short: "List a customer's vehicles",
	Use:   "vehicles <id>",
}

func runCustomersVehicles(cmd *cobra.Command, args []string) error {
	return runShow(cmd, args, "customers", "GET", func(a []string) string {
		return fmt.Sprintf("/customers/%s/vehicles", a[0])
	}, func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.ListCustomersVehicles(ctx, id)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var customersWorkordersCmd = &cobra.Command{
	Aliases: []string{"work-orders"},
	Args:    cobra.ExactArgs(1),
	RunE:    runCustomersWorkorders,
	Short:   "List a customer's work orders",
	Use:     "workorders <id>",
}

func runCustomersWorkorders(cmd *cobra.Command, args []string) error {
	return runShow(cmd, args, "customers", "GET", func(a []string) string {
		return fmt.Sprintf("/customers/%s/work_orders", a[0])
	}, func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.ListCustomersWorkOrders(ctx, id)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}
func customersListHasFilters() bool {
	if customersHasBalance {
		return true
	}
	if customersHasVehicle {
		return true
	}
	if customersLastVisitMonths > 0 {
		return true
	}
	if customersPage > 0 {
		return true
	}
	if customersPerPage > 0 {
		return true
	}
	if customersQ != "" {
		return true
	}
	if customersStatus != "" {
		return true
	}
	if customersType != "" {
		return true
	}
	return false
}

var customersCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "Manage customers",
	Use:   "customers",
}

func init() {
	customersDuplicatesCmd.Flags().StringVar(&customersEmail, "email", "", "Email")
	customersDuplicatesCmd.Flags().StringVar(&customersFirstName, "first-name", "", "First Name")
	customersDuplicatesCmd.Flags().StringVar(&customersLastName, "last-name", "", "Last Name")
	customersDuplicatesCmd.Flags().IntVar(&customersPhone, "phone", 0, "Phone")
	customersListCmd.Flags().BoolVar(&customersHasBalance, "has-balance", false, "Has Balance")
	customersListCmd.Flags().BoolVar(&customersHasVehicle, "has-vehicle", false, "Has Vehicle")
	customersListCmd.Flags().IntVar(&customersLastVisitMonths, "last-visit-months", 0, "Last Visit Months")
	customersListCmd.Flags().IntVar(&customersPage, "page", 0, "Page")
	customersListCmd.Flags().IntVar(&customersPerPage, "per-page", 0, "Per Page")
	customersListCmd.Flags().StringVar(&customersQ, "q", "", "Q")
	customersListCmd.Flags().StringVar(&customersStatus, "status", "", "Status")
	customersListCmd.Flags().IntSliceVar(&customersTagIds, "tag-ids", nil, "Filter by customer tag IDs (comma-separated)")
	customersListCmd.Flags().StringVar(&customersType, "type", "", "Type")
	customersListCmd.Flags().BoolVar(&customersListAll, "all", false, "Fetch all pages by following pagination links")
	customersMergeCmd.Flags().IntVar(&customersSourceCustomerId, "source-id", 0, "Source customer ID to merge into keeper (required)")
	customersMergeCmd.MarkFlagRequired("source-id")
	customersCmd.AddCommand(customersArchiveCmd, customersCreateCmd, customersDuplicatesCmd, customersListCmd, customersLookupCmd, customersMergeCmd, customersRestoreCmd, customersShowCmd, customersTrashCmd, customersVehiclesCmd, customersWorkordersCmd)
	rootCmd.AddCommand(customersCmd)
}
