// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var notificationsCreateCmd = &cobra.Command{
	RunE:  runNotificationsCreate,
	Short: "bulk_mark_read",
	Use:   "create",
}

func runNotificationsCreate(cmd *cobra.Command, args []string) error {
	return runSeedAction(cmd, "notifications", "/notifications/bulk_mark_read", "Notification create.", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.CreateNotificationsBulkMarkRead(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var notificationsCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "notifications commands",
	Use:   "notifications",
}

func init() {
	notificationsCmd.AddCommand(notificationsCreateCmd)
	rootCmd.AddCommand(notificationsCmd)
}
