// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var profileListCmd = &cobra.Command{
	RunE:  runProfileList,
	Short: "show",
	Use:   "list",
}

func runProfileList(cmd *cobra.Command, args []string) error {
	return runList(cmd, "profile", "/profile", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListProfile(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var profileCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "profile commands",
	Use:   "profile",
}

func init() {
	profileCmd.AddCommand(profileListCmd)
	rootCmd.AddCommand(profileCmd)
}
