// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var reportsFilterBillingStatus string
var reportsMarkedRemitted bool
var reportsPeriodEnd string
var reportsPeriodStart string
var reportsRemittedDate string
var reportsCreateCmd = &cobra.Command{
	Annotations: map[string]string{"wenmar/op": "POST /reports/tax_periods"},
	Example:     "wenmar reports create --period-start 2026-01-01 --period-end 2026-03-31\n",
	RunE:        runReportsCreate,
	Short:       "Create a tax period for remittance tracking",
	Use:         "create",
}

func runReportsCreate(cmd *cobra.Command, args []string) error {
	return runCreate(cmd, "reports", "/reports/tax_periods", "Tax period created.", func() (any, error) {
		req := wenmar.CreateReportsTaxPeriodRequest{TaxPeriod: struct {
			PeriodEnd   string `json:"period_end"`
			PeriodStart string `json:"period_start"`
		}{
			PeriodEnd:   reportsPeriodEnd,
			PeriodStart: reportsPeriodStart,
		}}
		return req, nil
	}, func(ctx context.Context, client *wenmar.Client, body any) (any, error) {
		resp, err := client.CreateReportsTaxPeriod(ctx, body.(wenmar.CreateReportsTaxPeriodRequest))
		if err != nil {
			return nil, err
		}
		return resp.JSON201, nil
	})
}

var reportsStatementsCmd = &cobra.Command{
	Annotations: map[string]string{"wenmar/op": "GET /reports/statements"},
	Example:     "wenmar reports statements\nwenmar reports statements --status sent\n",
	RunE:        runReportsStatements,
	Short:       "List account-wide statements",
	Use:         "statements",
}

func runReportsStatements(cmd *cobra.Command, args []string) error {
	return runList(cmd, "reports", "/reports/statements", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListReportsStatements(ctx, &wenmar.ListReportsStatementsParams{FilterBillingStatus: strPtr(reportsFilterBillingStatus)})
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var reportsTaxperiodsCmd = &cobra.Command{
	Annotations: map[string]string{"wenmar/op": "GET /reports/tax_periods"},
	Example:     "wenmar reports taxperiods\n",
	RunE:        runReportsTaxperiods,
	Short:       "List tax periods",
	Use:         "taxperiods",
}

func runReportsTaxperiods(cmd *cobra.Command, args []string) error {
	return runList(cmd, "reports", "/reports/tax_periods", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListReportsTaxPeriods(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var reportsUpdateCmd = &cobra.Command{
	Annotations: map[string]string{"wenmar/op": "PATCH /reports/tax_periods/{id}"},
	Args:        cobra.ExactArgs(1),
	Example:     "wenmar reports update 5 --marked-remitted --remitted-date 2026-04-15\n",
	RunE:        runReportsUpdate,
	Short:       "Update a tax period by ID",
	Use:         "update <id>",
}

func runReportsUpdate(cmd *cobra.Command, args []string) error {
	return runUpdate(cmd, args, "reports", idPath("/reports/tax_periods/"), "Tax period updated.", func(id int) (any, error) {
		req := wenmar.UpdateReportsTaxPeriodRequest{TaxPeriod: struct {
			MarkedRemitted bool   `json:"marked_remitted"`
			RemittedDate   string `json:"remitted_date"`
		}{
			MarkedRemitted: reportsMarkedRemitted,
			RemittedDate:   reportsRemittedDate,
		}}
		return req, nil
	}, func(ctx context.Context, client *wenmar.Client, id int, body any) (any, error) {
		resp, err := client.UpdateReportsTaxPeriod(ctx, id, body.(wenmar.UpdateReportsTaxPeriodRequest))
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var reportsCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "Manage report views and tax periods",
	Use:   "reports",
}

func init() {
	reportsCreateCmd.Flags().StringVar(&reportsPeriodEnd, "period-end", "", "Period End (required)")
	reportsCreateCmd.MarkFlagRequired("period-end")
	reportsCreateCmd.Flags().StringVar(&reportsPeriodStart, "period-start", "", "Period Start (required)")
	reportsCreateCmd.MarkFlagRequired("period-start")
	reportsStatementsCmd.Flags().StringVar(&reportsFilterBillingStatus, "billing-status", "", "Billing Status")
	reportsUpdateCmd.Flags().BoolVar(&reportsMarkedRemitted, "marked-remitted", false, "Marked Remitted (required)")
	reportsUpdateCmd.MarkFlagRequired("marked-remitted")
	reportsUpdateCmd.Flags().StringVar(&reportsRemittedDate, "remitted-date", "", "Remitted Date (required)")
	reportsUpdateCmd.MarkFlagRequired("remitted-date")
	reportsCmd.AddCommand(reportsCreateCmd, reportsStatementsCmd, reportsTaxperiodsCmd, reportsUpdateCmd)
	rootCmd.AddCommand(reportsCmd)
}
