// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var storeCreditsStoreCreditId int
var storeCreditsCreateCmd = &cobra.Command{
	RunE:  runStoreCreditsCreate,
	Short: "create",
	Use:   "create",
}

func runStoreCreditsCreate(cmd *cobra.Command, args []string) error {
	return runSeedAction(cmd, "store_credits", "/store_credits/{store_credit_id}/voids", "Store_credit create.", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.CreateStoreCreditsVoid(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var store_creditsCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "store_credits commands",
	Use:   "store_credits",
}

func init() {
	storeCreditsCreateCmd.Flags().IntVar(&storeCreditsStoreCreditId, "store-credit-id", 0, "Store Credit ID (required)")
	storeCreditsCreateCmd.MarkFlagRequired("store-credit-id")
	store_creditsCmd.AddCommand(storeCreditsCreateCmd)
	rootCmd.AddCommand(store_creditsCmd)
}
