// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var timeEntriesCreateCmd = &cobra.Command{
	RunE:  runTimeEntriesCreate,
	Short: "create",
	Use:   "create",
}

func runTimeEntriesCreate(cmd *cobra.Command, args []string) error {
	return runSeedAction(cmd, "time_entries", "/time_entries", "Time_entry create.", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.CreateTimeEntrie(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON201, nil
	})
}

var timeEntriesUpdateCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runTimeEntriesUpdate,
	Short: "update",
	Use:   "update <id>",
}

func runTimeEntriesUpdate(cmd *cobra.Command, args []string) error {
	return runUpdate(cmd, args, "time_entries", idPath("/time_entries/"), "Time_entry updated.", func(id int) (any, error) {
		return nil, nil
	}, func(ctx context.Context, client *wenmar.Client, id int, body any) (any, error) {
		return nil, nil
	})
}

var time_entriesCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "time_entries commands",
	Use:   "time_entries",
}

func init() {
	time_entriesCmd.AddCommand(timeEntriesCreateCmd, timeEntriesUpdateCmd)
	rootCmd.AddCommand(time_entriesCmd)
}
