// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var locationsShowCmd = &cobra.Command{
	Args:    cobra.ExactArgs(1),
	Example: "wenmar locations show main\n",
	RunE:    runLocationsShow,
	Short:   "Show a location by ID",
	Use:     "show <id>",
}

func runLocationsShow(cmd *cobra.Command, args []string) error {
	return runShowStr(cmd, args, "locations", "GET", idPath("/locations/"), func(ctx context.Context, client *wenmar.Client, id string) (any, error) {
		resp, err := client.ShowLocation(ctx, id)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var locationsCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "Show location details",
	Use:   "locations",
}

func init() {
	locationsCmd.AddCommand(locationsShowCmd)
	rootCmd.AddCommand(locationsCmd)
}
