// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var appointmentsDeleteDryRun bool
var appointmentsCreateCmd = &cobra.Command{
	RunE:  runAppointmentsCreate,
	Short: "create",
	Use:   "create",
}

func runAppointmentsCreate(cmd *cobra.Command, args []string) error {
	return runSeedAction(cmd, "appointments", "/appointments", "Appointment create.", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.CreateAppointment(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON201, nil
	})
}

var appointmentsDeleteCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runAppointmentsDelete,
	Short: "destroy",
	Use:   "delete <id>",
}

func runAppointmentsDelete(cmd *cobra.Command, args []string) error {
	return runDelete(cmd, args, "Appointment", "appointments", idPath("/appointments/"), appointmentsDeleteDryRun, func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		return client.DeleteAppointment(ctx, id)
	})
}

var appointmentsListCmd = &cobra.Command{
	RunE:  runAppointmentsList,
	Short: "index",
	Use:   "list",
}

func runAppointmentsList(cmd *cobra.Command, args []string) error {
	return runList(cmd, "appointments", "/appointments", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListAppointments(ctx, nil)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var appointmentsShowCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runAppointmentsShow,
	Short: "show",
	Use:   "show <id>",
}

func runAppointmentsShow(cmd *cobra.Command, args []string) error {
	return runShow(cmd, args, "appointments", "GET", idPath("/appointments/"), func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.ShowAppointment(ctx, id)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var appointmentsUpdateCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runAppointmentsUpdate,
	Short: "update",
	Use:   "update <id>",
}

func runAppointmentsUpdate(cmd *cobra.Command, args []string) error {
	return runUpdate(cmd, args, "appointments", idPath("/appointments/"), "Appointment updated.", func(id int) (any, error) {
		return nil, nil
	}, func(ctx context.Context, client *wenmar.Client, id int, body any) (any, error) {
		return nil, nil
	})
}

var appointmentsCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "appointments commands",
	Use:   "appointments",
}

func init() {
	appointmentsDeleteCmd.Flags().BoolVar(&appointmentsDeleteDryRun, "dry-run", false, "Preview what would be deleted without making an API call")
	appointmentsCmd.AddCommand(appointmentsCreateCmd, appointmentsDeleteCmd, appointmentsListCmd, appointmentsShowCmd, appointmentsUpdateCmd)
	rootCmd.AddCommand(appointmentsCmd)
}
