// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var aiSuggestionsUpdateCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runAiSuggestionsUpdate,
	Short: "update",
	Use:   "update <id>",
}

func runAiSuggestionsUpdate(cmd *cobra.Command, args []string) error {
	return runUpdate(cmd, args, "ai_suggestions", idPath("/ai_suggestions/"), "Ai_suggestion updated.", func(id int) (any, error) {
		return nil, nil
	}, func(ctx context.Context, client *wenmar.Client, id int, body any) (any, error) {
		return nil, nil
	})
}

var ai_suggestionsCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "ai_suggestions commands",
	Use:   "ai_suggestions",
}

func init() {
	ai_suggestionsCmd.AddCommand(aiSuggestionsUpdateCmd)
	rootCmd.AddCommand(ai_suggestionsCmd)
}
