// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var leadSourcesDeleteDryRun bool
var leadSourcesCreateCmd = &cobra.Command{
	RunE:  runLeadSourcesCreate,
	Short: "create",
	Use:   "create",
}

func runLeadSourcesCreate(cmd *cobra.Command, args []string) error {
	return runSeedAction(cmd, "lead_sources", "/lead_sources", "Lead_source create.", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.CreateLeadSource(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON201, nil
	})
}

var leadSourcesDeleteCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runLeadSourcesDelete,
	Short: "destroy",
	Use:   "delete <id>",
}

func runLeadSourcesDelete(cmd *cobra.Command, args []string) error {
	return runDelete(cmd, args, "Lead_source", "lead_sources", idPath("/lead_sources/"), leadSourcesDeleteDryRun, func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		return client.DeleteLeadSource(ctx, id)
	})
}

var leadSourcesListCmd = &cobra.Command{
	RunE:  runLeadSourcesList,
	Short: "index",
	Use:   "list",
}

func runLeadSourcesList(cmd *cobra.Command, args []string) error {
	return runList(cmd, "lead_sources", "/lead_sources", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListLeadSources(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var leadSourcesUpdateCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runLeadSourcesUpdate,
	Short: "update",
	Use:   "update <id>",
}

func runLeadSourcesUpdate(cmd *cobra.Command, args []string) error {
	return runUpdate(cmd, args, "lead_sources", idPath("/lead_sources/"), "Lead_source updated.", func(id int) (any, error) {
		return nil, nil
	}, func(ctx context.Context, client *wenmar.Client, id int, body any) (any, error) {
		return nil, nil
	})
}

var lead_sourcesCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "lead_sources commands",
	Use:   "lead_sources",
}

func init() {
	leadSourcesDeleteCmd.Flags().BoolVar(&leadSourcesDeleteDryRun, "dry-run", false, "Preview what would be deleted without making an API call")
	lead_sourcesCmd.AddCommand(leadSourcesCreateCmd, leadSourcesDeleteCmd, leadSourcesListCmd, leadSourcesUpdateCmd)
	rootCmd.AddCommand(lead_sourcesCmd)
}
