// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	"fmt"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var paymentsCreateCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runPaymentsCreate,
	Short: "create",
	Use:   "create <id>",
}

func runPaymentsCreate(cmd *cobra.Command, args []string) error {
	return runActionNoBody(cmd, args, "payments", "POST", func(a []string) string {
		return fmt.Sprintf("/payments/%s/cancellation", a[0])
	}, "Payment create.", func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.CreatePaymentsCancellation(ctx, id)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var paymentsListCmd = &cobra.Command{
	RunE:  runPaymentsList,
	Short: "index",
	Use:   "list",
}

func runPaymentsList(cmd *cobra.Command, args []string) error {
	return runList(cmd, "payments", "/payments", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListPayments(ctx, nil)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var paymentsShowCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runPaymentsShow,
	Short: "show",
	Use:   "show <id>",
}

func runPaymentsShow(cmd *cobra.Command, args []string) error {
	return runShow(cmd, args, "payments", "GET", idPath("/payments/"), func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.ShowPayment(ctx, id)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var paymentsCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "payments commands",
	Use:   "payments",
}

func init() {
	paymentsCmd.AddCommand(paymentsCreateCmd, paymentsListCmd, paymentsShowCmd)
	rootCmd.AddCommand(paymentsCmd)
}
