// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var searchListCmd = &cobra.Command{
	RunE:  runSearchList,
	Short: "results",
	Use:   "list",
}

func runSearchList(cmd *cobra.Command, args []string) error {
	return runList(cmd, "search", "/search", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListSearch(ctx, nil)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var searchCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "search commands",
	Use:   "search",
}

func init() {
	searchCmd.AddCommand(searchListCmd)
	rootCmd.AddCommand(searchCmd)
}
