// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var vendorsListCmd = &cobra.Command{
	Example: "wenmar vendors list\n",
	RunE:    runVendorsList,
	Short:   "List all vendors, paginated via the Link header",
	Use:     "list",
}

func runVendorsList(cmd *cobra.Command, args []string) error {
	return runList(cmd, "vendors", "/vendors", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListVendors(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var vendorsShowCmd = &cobra.Command{
	Args:    cobra.ExactArgs(1),
	Example: "wenmar vendors show 7\n",
	RunE:    runVendorsShow,
	Short:   "Show a single vendor by ID",
	Use:     "show <id>",
}

func runVendorsShow(cmd *cobra.Command, args []string) error {
	return runShow(cmd, args, "vendors", "GET", idPath("/vendors/"), func(ctx context.Context, client *wenmar.Client, id int) (any, error) {
		resp, err := client.ShowVendor(ctx, id)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var vendorsCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "Manage vendors",
	Use:   "vendors",
}

func init() {
	vendorsCmd.AddCommand(vendorsListCmd, vendorsShowCmd)
	rootCmd.AddCommand(vendorsCmd)
}
