// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	"fmt"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var counterSalesCounterSaleId int
var counterSalesListCmd = &cobra.Command{
	RunE:  runCounterSalesList,
	Short: "brands",
	Use:   "list",
}

func runCounterSalesList(cmd *cobra.Command, args []string) error {
	return runList(cmd, "counter_sales", fmt.Sprintf("/counter_sales/%d/line_items/brands", counterSalesCounterSaleId), func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListCounterSalesLineItemsBrands(ctx, counterSalesCounterSaleId)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var counter_salesCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "counter_sales commands",
	Use:   "counter_sales",
}

func init() {
	counterSalesListCmd.Flags().IntVar(&counterSalesCounterSaleId, "counter-sale-id", 0, "Counter Sale ID (required)")
	counterSalesListCmd.MarkFlagRequired("counter-sale-id")
	counter_salesCmd.AddCommand(counterSalesListCmd)
	rootCmd.AddCommand(counter_salesCmd)
}
