// Code generated by gencli. DO NOT EDIT.
//go:build ignore

package cmd

import (
	"context"
	cobra "github.com/spf13/cobra"
	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

var coreTaxRulesListCmd = &cobra.Command{
	RunE:  runCoreTaxRulesList,
	Short: "index",
	Use:   "list",
}

func runCoreTaxRulesList(cmd *cobra.Command, args []string) error {
	return runList(cmd, "core_tax_rules", "/core_tax_rules", func(ctx context.Context, client *wenmar.Client) (any, error) {
		resp, err := client.ListCoreTaxRules(ctx)
		if err != nil {
			return nil, err
		}
		return resp.JSON200, nil
	})
}

var coreTaxRulesUpdateCmd = &cobra.Command{
	Args:  cobra.ExactArgs(1),
	RunE:  runCoreTaxRulesUpdate,
	Short: "update",
	Use:   "update <id>",
}

func runCoreTaxRulesUpdate(cmd *cobra.Command, args []string) error {
	return runUpdate(cmd, args, "core_tax_rules", idPath("/core_tax_rules/"), "Core_tax_rule updated.", func(id int) (any, error) {
		return nil, nil
	}, func(ctx context.Context, client *wenmar.Client, id int, body any) (any, error) {
		return nil, nil
	})
}

var core_tax_rulesCmd = &cobra.Command{
	Args:    cobra.NoArgs,
	GroupID: "resources",
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
	Short: "core_tax_rules commands",
	Use:   "core_tax_rules",
}

func init() {
	core_tax_rulesCmd.AddCommand(coreTaxRulesListCmd, coreTaxRulesUpdateCmd)
	rootCmd.AddCommand(core_tax_rulesCmd)
}
